run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - revive
    - gofumpt

issues:
  exclude-dirs:
    - proto
  exclude-files:
    - ".*\\.pb\\.go$"
