// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/lettuce/v1/volunteer.proto

package lettucev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VolunteerService_GetServerStatus_FullMethodName          = "/lettuce.volunteer.v1.VolunteerService/GetServerStatus"
	VolunteerService_RegisterVolunteer_FullMethodName        = "/lettuce.volunteer.v1.VolunteerService/RegisterVolunteer"
	VolunteerService_GetRegistrationChallenge_FullMethodName = "/lettuce.volunteer.v1.VolunteerService/GetRegistrationChallenge"
	VolunteerService_RequestWorkUnit_FullMethodName          = "/lettuce.volunteer.v1.VolunteerService/RequestWorkUnit"
	VolunteerService_SubmitResult_FullMethodName             = "/lettuce.volunteer.v1.VolunteerService/SubmitResult"
	VolunteerService_StartWork_FullMethodName                = "/lettuce.volunteer.v1.VolunteerService/StartWork"
	VolunteerService_GetWorkUnitStatus_FullMethodName        = "/lettuce.volunteer.v1.VolunteerService/GetWorkUnitStatus"
	VolunteerService_GetHeadInfo_FullMethodName              = "/lettuce.volunteer.v1.VolunteerService/GetHeadInfo"
	VolunteerService_SaveCheckpoint_FullMethodName           = "/lettuce.volunteer.v1.VolunteerService/SaveCheckpoint"
	VolunteerService_GetCheckpoint_FullMethodName            = "/lettuce.volunteer.v1.VolunteerService/GetCheckpoint"
	VolunteerService_AbandonWorkUnit_FullMethodName          = "/lettuce.volunteer.v1.VolunteerService/AbandonWorkUnit"
	VolunteerService_GetMyContribution_FullMethodName        = "/lettuce.volunteer.v1.VolunteerService/GetMyContribution"
)

// VolunteerServiceClient is the client API for VolunteerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VolunteerServiceClient interface {
	// Returns server status and version information.
	GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*GetServerStatusResponse, error)
	// Register or update volunteer capabilities.
	// Called on first connection and when hardware config changes.
	// Upserts by public_key: new key = register, existing key = update.
	RegisterVolunteer(ctx context.Context, in *RegisterVolunteerRequest, opts ...grpc.CallOption) (*RegisterVolunteerResponse, error)
	// Issue a registration proof-of-work challenge for the CALLER's key (derived
	// from the verified per-request signature, like RegisterVolunteer — the key
	// need not be registered yet). Relevant only when the head enforces
	// registration proof-of-work: a brand-new key's RegisterVolunteer is then
	// refused with FailedPrecondition until it carries a valid solution
	// (pow_challenge_id + pow_nonce). Solve by finding a nonce such that
	// SHA-256(challenge || public_key || nonce as 8 big-endian bytes) has at
	// least difficulty_bits leading zero bits. Challenges expire and are
	// single-use. Re-registration of an existing key never requires this.
	GetRegistrationChallenge(ctx context.Context, in *GetRegistrationChallengeRequest, opts ...grpc.CallOption) (*GetRegistrationChallengeResponse, error)
	// Request work units matching volunteer capabilities.
	// Returns 0..N assignments and a server-directed `retry_after_seconds` the
	// caller MUST obey before its next call (present on all replies, including
	// no-work). Each assignment carries `reserved_until_unix`, the lease window
	// during which the head will not reclaim the unit.
	RequestWorkUnit(ctx context.Context, in *RequestWorkUnitRequest, opts ...grpc.CallOption) (*RequestWorkUnitResponse, error)
	// Submit result for a completed work unit.
	// Includes output data and execution metadata.
	SubmitResult(ctx context.Context, in *SubmitResultRequest, opts ...grpc.CallOption) (*SubmitResultResponse, error)
	// Mark a buffered (reserved) work unit as run-started. Called when a volunteer
	// slot actually begins executing a unit pulled from its client work buffer.
	// Performs the QUEUED -> ASSIGNED run-start transition (clears the reservation
	// column, writes the active assignment history row, starts the deadline clock).
	// Liveness is deadline-based: there are no per-task heartbeats. A unit not
	// submitted by its deadline is reassigned; a reserved unit whose reservation
	// window lapses before StartWork is reclaimed.
	StartWork(ctx context.Context, in *StartWorkRequest, opts ...grpc.CallOption) (*StartWorkResponse, error)
	// Query status of a specific work unit.
	GetWorkUnitStatus(ctx context.Context, in *GetWorkUnitStatusRequest, opts ...grpc.CallOption) (*GetWorkUnitStatusResponse, error)
	// Get head identity and active leaf discovery info.
	GetHeadInfo(ctx context.Context, in *GetHeadInfoRequest, opts ...grpc.CallOption) (*GetHeadInfoResponse, error)
	// Save a checkpoint for a running work unit.
	SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error)
	// Get the latest checkpoint for a work unit.
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error)
	// Abandon a work unit that the volunteer cannot execute (e.g., prepare failed).
	// Server marks the assignment as ABANDONED and requeues the work unit.
	AbandonWorkUnit(ctx context.Context, in *AbandonWorkUnitRequest, opts ...grpc.CallOption) (*AbandonWorkUnitResponse, error)
	// Return the CALLER's own credit contribution, aggregated across every leaf and
	// every machine the caller runs. Credit is keyed to the ACCOUNT (the Ed25519
	// identity key), not the host, so this already sums a volunteer's machines into
	// one total. The caller's identity is derived from the VERIFIED per-request
	// signature (the authenticated public key), NOT from any request field — so a
	// volunteer can only ever see its own credit. Authenticated (not a public
	// method). This is the self-service counterpart to the operator-only REST
	// endpoint GET /api/v1/volunteers/{id}/credit/breakdown.
	GetMyContribution(ctx context.Context, in *GetMyContributionRequest, opts ...grpc.CallOption) (*GetMyContributionResponse, error)
}

type volunteerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVolunteerServiceClient(cc grpc.ClientConnInterface) VolunteerServiceClient {
	return &volunteerServiceClient{cc}
}

func (c *volunteerServiceClient) GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*GetServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerStatusResponse)
	err := c.cc.Invoke(ctx, VolunteerService_GetServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) RegisterVolunteer(ctx context.Context, in *RegisterVolunteerRequest, opts ...grpc.CallOption) (*RegisterVolunteerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterVolunteerResponse)
	err := c.cc.Invoke(ctx, VolunteerService_RegisterVolunteer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) GetRegistrationChallenge(ctx context.Context, in *GetRegistrationChallengeRequest, opts ...grpc.CallOption) (*GetRegistrationChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegistrationChallengeResponse)
	err := c.cc.Invoke(ctx, VolunteerService_GetRegistrationChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) RequestWorkUnit(ctx context.Context, in *RequestWorkUnitRequest, opts ...grpc.CallOption) (*RequestWorkUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestWorkUnitResponse)
	err := c.cc.Invoke(ctx, VolunteerService_RequestWorkUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) SubmitResult(ctx context.Context, in *SubmitResultRequest, opts ...grpc.CallOption) (*SubmitResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResultResponse)
	err := c.cc.Invoke(ctx, VolunteerService_SubmitResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) StartWork(ctx context.Context, in *StartWorkRequest, opts ...grpc.CallOption) (*StartWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkResponse)
	err := c.cc.Invoke(ctx, VolunteerService_StartWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) GetWorkUnitStatus(ctx context.Context, in *GetWorkUnitStatusRequest, opts ...grpc.CallOption) (*GetWorkUnitStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkUnitStatusResponse)
	err := c.cc.Invoke(ctx, VolunteerService_GetWorkUnitStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) GetHeadInfo(ctx context.Context, in *GetHeadInfoRequest, opts ...grpc.CallOption) (*GetHeadInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHeadInfoResponse)
	err := c.cc.Invoke(ctx, VolunteerService_GetHeadInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCheckpointResponse)
	err := c.cc.Invoke(ctx, VolunteerService_SaveCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckpointResponse)
	err := c.cc.Invoke(ctx, VolunteerService_GetCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) AbandonWorkUnit(ctx context.Context, in *AbandonWorkUnitRequest, opts ...grpc.CallOption) (*AbandonWorkUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonWorkUnitResponse)
	err := c.cc.Invoke(ctx, VolunteerService_AbandonWorkUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) GetMyContribution(ctx context.Context, in *GetMyContributionRequest, opts ...grpc.CallOption) (*GetMyContributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyContributionResponse)
	err := c.cc.Invoke(ctx, VolunteerService_GetMyContribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolunteerServiceServer is the server API for VolunteerService service.
// All implementations must embed UnimplementedVolunteerServiceServer
// for forward compatibility.
type VolunteerServiceServer interface {
	// Returns server status and version information.
	GetServerStatus(context.Context, *GetServerStatusRequest) (*GetServerStatusResponse, error)
	// Register or update volunteer capabilities.
	// Called on first connection and when hardware config changes.
	// Upserts by public_key: new key = register, existing key = update.
	RegisterVolunteer(context.Context, *RegisterVolunteerRequest) (*RegisterVolunteerResponse, error)
	// Issue a registration proof-of-work challenge for the CALLER's key (derived
	// from the verified per-request signature, like RegisterVolunteer — the key
	// need not be registered yet). Relevant only when the head enforces
	// registration proof-of-work: a brand-new key's RegisterVolunteer is then
	// refused with FailedPrecondition until it carries a valid solution
	// (pow_challenge_id + pow_nonce). Solve by finding a nonce such that
	// SHA-256(challenge || public_key || nonce as 8 big-endian bytes) has at
	// least difficulty_bits leading zero bits. Challenges expire and are
	// single-use. Re-registration of an existing key never requires this.
	GetRegistrationChallenge(context.Context, *GetRegistrationChallengeRequest) (*GetRegistrationChallengeResponse, error)
	// Request work units matching volunteer capabilities.
	// Returns 0..N assignments and a server-directed `retry_after_seconds` the
	// caller MUST obey before its next call (present on all replies, including
	// no-work). Each assignment carries `reserved_until_unix`, the lease window
	// during which the head will not reclaim the unit.
	RequestWorkUnit(context.Context, *RequestWorkUnitRequest) (*RequestWorkUnitResponse, error)
	// Submit result for a completed work unit.
	// Includes output data and execution metadata.
	SubmitResult(context.Context, *SubmitResultRequest) (*SubmitResultResponse, error)
	// Mark a buffered (reserved) work unit as run-started. Called when a volunteer
	// slot actually begins executing a unit pulled from its client work buffer.
	// Performs the QUEUED -> ASSIGNED run-start transition (clears the reservation
	// column, writes the active assignment history row, starts the deadline clock).
	// Liveness is deadline-based: there are no per-task heartbeats. A unit not
	// submitted by its deadline is reassigned; a reserved unit whose reservation
	// window lapses before StartWork is reclaimed.
	StartWork(context.Context, *StartWorkRequest) (*StartWorkResponse, error)
	// Query status of a specific work unit.
	GetWorkUnitStatus(context.Context, *GetWorkUnitStatusRequest) (*GetWorkUnitStatusResponse, error)
	// Get head identity and active leaf discovery info.
	GetHeadInfo(context.Context, *GetHeadInfoRequest) (*GetHeadInfoResponse, error)
	// Save a checkpoint for a running work unit.
	SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error)
	// Get the latest checkpoint for a work unit.
	GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error)
	// Abandon a work unit that the volunteer cannot execute (e.g., prepare failed).
	// Server marks the assignment as ABANDONED and requeues the work unit.
	AbandonWorkUnit(context.Context, *AbandonWorkUnitRequest) (*AbandonWorkUnitResponse, error)
	// Return the CALLER's own credit contribution, aggregated across every leaf and
	// every machine the caller runs. Credit is keyed to the ACCOUNT (the Ed25519
	// identity key), not the host, so this already sums a volunteer's machines into
	// one total. The caller's identity is derived from the VERIFIED per-request
	// signature (the authenticated public key), NOT from any request field — so a
	// volunteer can only ever see its own credit. Authenticated (not a public
	// method). This is the self-service counterpart to the operator-only REST
	// endpoint GET /api/v1/volunteers/{id}/credit/breakdown.
	GetMyContribution(context.Context, *GetMyContributionRequest) (*GetMyContributionResponse, error)
	mustEmbedUnimplementedVolunteerServiceServer()
}

// UnimplementedVolunteerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolunteerServiceServer struct{}

func (UnimplementedVolunteerServiceServer) GetServerStatus(context.Context, *GetServerStatusRequest) (*GetServerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerStatus not implemented")
}
func (UnimplementedVolunteerServiceServer) RegisterVolunteer(context.Context, *RegisterVolunteerRequest) (*RegisterVolunteerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterVolunteer not implemented")
}
func (UnimplementedVolunteerServiceServer) GetRegistrationChallenge(context.Context, *GetRegistrationChallengeRequest) (*GetRegistrationChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegistrationChallenge not implemented")
}
func (UnimplementedVolunteerServiceServer) RequestWorkUnit(context.Context, *RequestWorkUnitRequest) (*RequestWorkUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestWorkUnit not implemented")
}
func (UnimplementedVolunteerServiceServer) SubmitResult(context.Context, *SubmitResultRequest) (*SubmitResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResult not implemented")
}
func (UnimplementedVolunteerServiceServer) StartWork(context.Context, *StartWorkRequest) (*StartWorkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWork not implemented")
}
func (UnimplementedVolunteerServiceServer) GetWorkUnitStatus(context.Context, *GetWorkUnitStatusRequest) (*GetWorkUnitStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkUnitStatus not implemented")
}
func (UnimplementedVolunteerServiceServer) GetHeadInfo(context.Context, *GetHeadInfoRequest) (*GetHeadInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHeadInfo not implemented")
}
func (UnimplementedVolunteerServiceServer) SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCheckpoint not implemented")
}
func (UnimplementedVolunteerServiceServer) GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedVolunteerServiceServer) AbandonWorkUnit(context.Context, *AbandonWorkUnitRequest) (*AbandonWorkUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbandonWorkUnit not implemented")
}
func (UnimplementedVolunteerServiceServer) GetMyContribution(context.Context, *GetMyContributionRequest) (*GetMyContributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyContribution not implemented")
}
func (UnimplementedVolunteerServiceServer) mustEmbedUnimplementedVolunteerServiceServer() {}
func (UnimplementedVolunteerServiceServer) testEmbeddedByValue()                          {}

// UnsafeVolunteerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolunteerServiceServer will
// result in compilation errors.
type UnsafeVolunteerServiceServer interface {
	mustEmbedUnimplementedVolunteerServiceServer()
}

func RegisterVolunteerServiceServer(s grpc.ServiceRegistrar, srv VolunteerServiceServer) {
	// If the following call panics, it indicates UnimplementedVolunteerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolunteerService_ServiceDesc, srv)
}

func _VolunteerService_GetServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).GetServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_GetServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).GetServerStatus(ctx, req.(*GetServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_RegisterVolunteer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterVolunteerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).RegisterVolunteer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_RegisterVolunteer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).RegisterVolunteer(ctx, req.(*RegisterVolunteerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_GetRegistrationChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegistrationChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).GetRegistrationChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_GetRegistrationChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).GetRegistrationChallenge(ctx, req.(*GetRegistrationChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_RequestWorkUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestWorkUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).RequestWorkUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_RequestWorkUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).RequestWorkUnit(ctx, req.(*RequestWorkUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_SubmitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).SubmitResult(ctx, req.(*SubmitResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_StartWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).StartWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_StartWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).StartWork(ctx, req.(*StartWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_GetWorkUnitStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkUnitStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).GetWorkUnitStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_GetWorkUnitStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).GetWorkUnitStatus(ctx, req.(*GetWorkUnitStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_GetHeadInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeadInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).GetHeadInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_GetHeadInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).GetHeadInfo(ctx, req.(*GetHeadInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_SaveCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).SaveCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_SaveCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).SaveCheckpoint(ctx, req.(*SaveCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_GetCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).GetCheckpoint(ctx, req.(*GetCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_AbandonWorkUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonWorkUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).AbandonWorkUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_AbandonWorkUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).AbandonWorkUnit(ctx, req.(*AbandonWorkUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_GetMyContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyContributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).GetMyContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_GetMyContribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).GetMyContribution(ctx, req.(*GetMyContributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VolunteerService_ServiceDesc is the grpc.ServiceDesc for VolunteerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolunteerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lettuce.volunteer.v1.VolunteerService",
	HandlerType: (*VolunteerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerStatus",
			Handler:    _VolunteerService_GetServerStatus_Handler,
		},
		{
			MethodName: "RegisterVolunteer",
			Handler:    _VolunteerService_RegisterVolunteer_Handler,
		},
		{
			MethodName: "GetRegistrationChallenge",
			Handler:    _VolunteerService_GetRegistrationChallenge_Handler,
		},
		{
			MethodName: "RequestWorkUnit",
			Handler:    _VolunteerService_RequestWorkUnit_Handler,
		},
		{
			MethodName: "SubmitResult",
			Handler:    _VolunteerService_SubmitResult_Handler,
		},
		{
			MethodName: "StartWork",
			Handler:    _VolunteerService_StartWork_Handler,
		},
		{
			MethodName: "GetWorkUnitStatus",
			Handler:    _VolunteerService_GetWorkUnitStatus_Handler,
		},
		{
			MethodName: "GetHeadInfo",
			Handler:    _VolunteerService_GetHeadInfo_Handler,
		},
		{
			MethodName: "SaveCheckpoint",
			Handler:    _VolunteerService_SaveCheckpoint_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _VolunteerService_GetCheckpoint_Handler,
		},
		{
			MethodName: "AbandonWorkUnit",
			Handler:    _VolunteerService_AbandonWorkUnit_Handler,
		},
		{
			MethodName: "GetMyContribution",
			Handler:    _VolunteerService_GetMyContribution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lettuce/v1/volunteer.proto",
}
