// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/lettuce/v1/volunteer.proto

package lettucev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatusRequest) Reset() {
	*x = GetServerStatusRequest{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusRequest) ProtoMessage() {}

func (x *GetServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{0}
}

type GetServerStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	DatabaseStatus string                 `protobuf:"bytes,4,opt,name=database_status,json=databaseStatus,proto3" json:"database_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetServerStatusResponse) Reset() {
	*x = GetServerStatusResponse{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusResponse) ProtoMessage() {}

func (x *GetServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetServerStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetServerStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetServerStatusResponse) GetDatabaseStatus() string {
	if x != nil {
		return x.DatabaseStatus
	}
	return ""
}

type RegisterVolunteerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicKey         []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`       // Ed25519 public key (32 bytes)
	DisplayName       string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // optional
	Hardware          *HardwareCapabilities  `protobuf:"bytes,3,opt,name=hardware,proto3" json:"hardware,omitempty"`
	AvailableRuntimes []string               `protobuf:"bytes,4,rep,name=available_runtimes,json=availableRuntimes,proto3" json:"available_runtimes,omitempty"` // ["NATIVE", "CONTAINER"]
	SchedulingMode    string                 `protobuf:"bytes,5,opt,name=scheduling_mode,json=schedulingMode,proto3" json:"scheduling_mode,omitempty"`          // ALWAYS, WHEN_IDLE, SCHEDULED
	// Stable per-MACHINE host identifier the volunteer self-generates and persists in
	// its data dir (alongside the keypair). The keypair is the ACCOUNT — one user runs
	// the SAME key on every machine — and this distinguishes the machines under it so
	// per-machine facts (advertised runtimes/hardware, in-flight cap, work-send floor,
	// last-seen, work attribution) are tracked per host while credit/distinctness stay
	// per account. ADDITIVE: an empty host_id falls back to per-account behavior (host
	// == account), so a volunteer that sends none is not a breaking cutover. It is
	// signed under the identity key for free — the per-request signature covers the
	// whole request — so nobody else can claim your machine.
	HostId        string `protobuf:"bytes,6,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterVolunteerRequest) Reset() {
	*x = RegisterVolunteerRequest{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVolunteerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVolunteerRequest) ProtoMessage() {}

func (x *RegisterVolunteerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVolunteerRequest.ProtoReflect.Descriptor instead.
func (*RegisterVolunteerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterVolunteerRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegisterVolunteerRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RegisterVolunteerRequest) GetHardware() *HardwareCapabilities {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *RegisterVolunteerRequest) GetAvailableRuntimes() []string {
	if x != nil {
		return x.AvailableRuntimes
	}
	return nil
}

func (x *RegisterVolunteerRequest) GetSchedulingMode() string {
	if x != nil {
		return x.SchedulingMode
	}
	return ""
}

func (x *RegisterVolunteerRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type RegisterVolunteerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolunteerId   string                 `protobuf:"bytes,1,opt,name=volunteer_id,json=volunteerId,proto3" json:"volunteer_id,omitempty"` // assigned UUID
	Registered    bool                   `protobuf:"varint,2,opt,name=registered,proto3" json:"registered,omitempty"`                     // true if new registration, false if updated existing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterVolunteerResponse) Reset() {
	*x = RegisterVolunteerResponse{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVolunteerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVolunteerResponse) ProtoMessage() {}

func (x *RegisterVolunteerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVolunteerResponse.ProtoReflect.Descriptor instead.
func (*RegisterVolunteerResponse) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterVolunteerResponse) GetVolunteerId() string {
	if x != nil {
		return x.VolunteerId
	}
	return ""
}

func (x *RegisterVolunteerResponse) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

type RequestWorkUnitRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VolunteerId      string                 `protobuf:"bytes,1,opt,name=volunteer_id,json=volunteerId,proto3" json:"volunteer_id,omitempty"`
	PublicKey        []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                      // 32-byte Ed25519, for auth verification
	CurrentAvailable *HardwareCapabilities  `protobuf:"bytes,3,opt,name=current_available,json=currentAvailable,proto3" json:"current_available,omitempty"` // current free resources
	LeafIds          []string               `protobuf:"bytes,4,rep,name=leaf_ids,json=leafIds,proto3" json:"leaf_ids,omitempty"`                            // empty = any matching leaf
	BlockedLeafIds   []string               `protobuf:"bytes,5,rep,name=blocked_leaf_ids,json=blockedLeafIds,proto3" json:"blocked_leaf_ids,omitempty"`
	MaxAssignments   int32                  `protobuf:"varint,6,opt,name=max_assignments,json=maxAssignments,proto3" json:"max_assignments,omitempty"` // client's requested batch size (server-capped)
	// The work units the volunteer currently holds in its client buffer: every
	// buffered (not-yet-run-started) and running unit. The head reconciles its
	// per-volunteer reservations against this set on each request, releasing any
	// buffered reservation the volunteer no longer holds (e.g. dropped across a
	// client restart) so it stops counting against the volunteer's inflight cap
	// and the unit redispatches immediately. An empty list means the volunteer
	// holds nothing. Sent on every request; the head treats it as authoritative.
	HeldWorkUnitIds []string `protobuf:"bytes,7,rep,name=held_work_unit_ids,json=heldWorkUnitIds,proto3" json:"held_work_unit_ids,omitempty"`
	// Stable per-MACHINE host id (see RegisterVolunteerRequest.host_id). The head keys
	// the per-machine in-flight cap and work-send-interval floor on this, attributes the
	// copy rows this request reserves to it, and reconciles the held_work_unit_ids buffer
	// per host — so a user's beefy rig and laptop each get an independent work budget and
	// never evict each other's buffers. Per-WU distinctness still keys on the ACCOUNT, so
	// a user's own machines never corroborate the same unit. ADDITIVE: empty = per-account
	// behavior (host == account). Signed under the identity key via the request signature.
	HostId        string `protobuf:"bytes,8,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWorkUnitRequest) Reset() {
	*x = RequestWorkUnitRequest{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWorkUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWorkUnitRequest) ProtoMessage() {}

func (x *RequestWorkUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWorkUnitRequest.ProtoReflect.Descriptor instead.
func (*RequestWorkUnitRequest) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{4}
}

func (x *RequestWorkUnitRequest) GetVolunteerId() string {
	if x != nil {
		return x.VolunteerId
	}
	return ""
}

func (x *RequestWorkUnitRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RequestWorkUnitRequest) GetCurrentAvailable() *HardwareCapabilities {
	if x != nil {
		return x.CurrentAvailable
	}
	return nil
}

func (x *RequestWorkUnitRequest) GetLeafIds() []string {
	if x != nil {
		return x.LeafIds
	}
	return nil
}

func (x *RequestWorkUnitRequest) GetBlockedLeafIds() []string {
	if x != nil {
		return x.BlockedLeafIds
	}
	return nil
}

func (x *RequestWorkUnitRequest) GetMaxAssignments() int32 {
	if x != nil {
		return x.MaxAssignments
	}
	return 0
}

func (x *RequestWorkUnitRequest) GetHeldWorkUnitIds() []string {
	if x != nil {
		return x.HeldWorkUnitIds
	}
	return nil
}

func (x *RequestWorkUnitRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type RequestWorkUnitResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Assignments       []*WorkUnitAssignment  `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`                                         // 0..N units; empty = no work right now
	RetryAfterSeconds int32                  `protobuf:"varint,2,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"` // server-directed retry delay (authoritative)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RequestWorkUnitResponse) Reset() {
	*x = RequestWorkUnitResponse{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWorkUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWorkUnitResponse) ProtoMessage() {}

func (x *RequestWorkUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWorkUnitResponse.ProtoReflect.Descriptor instead.
func (*RequestWorkUnitResponse) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{5}
}

func (x *RequestWorkUnitResponse) GetAssignments() []*WorkUnitAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *RequestWorkUnitResponse) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

// WorkUnitAssignment is a single work unit dispatched to a volunteer. A
// RequestWorkUnitResponse carries 0..N of these (work batching).
type WorkUnitAssignment struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	WorkUnitId                string                 `protobuf:"bytes,1,opt,name=work_unit_id,json=workUnitId,proto3" json:"work_unit_id,omitempty"`
	LeafId                    string                 `protobuf:"bytes,2,opt,name=leaf_id,json=leafId,proto3" json:"leaf_id,omitempty"`
	Runtime                   string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`                                          // native, container, etc.
	InputData                 []byte                 `protobuf:"bytes,4,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`                     // inline data (< 1 MB)
	InputDataUrl              string                 `protobuf:"bytes,5,opt,name=input_data_url,json=inputDataUrl,proto3" json:"input_data_url,omitempty"`          // URL for external data
	CodeArtifactUrl           string                 `protobuf:"bytes,6,opt,name=code_artifact_url,json=codeArtifactUrl,proto3" json:"code_artifact_url,omitempty"` // URL to download code/binary
	ParametersJson            string                 `protobuf:"bytes,7,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`      // parameter set as JSON string
	DeadlineSeconds           int32                  `protobuf:"varint,8,opt,name=deadline_seconds,json=deadlineSeconds,proto3" json:"deadline_seconds,omitempty"`
	EnvVars                   map[string]string      `protobuf:"bytes,10,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExecutionSpec             *ExecutionSpec         `protobuf:"bytes,11,opt,name=execution_spec,json=executionSpec,proto3" json:"execution_spec,omitempty"`
	HasCheckpoint             bool                   `protobuf:"varint,12,opt,name=has_checkpoint,json=hasCheckpoint,proto3" json:"has_checkpoint,omitempty"`                                       // true if a checkpoint exists for this reassigned WU
	CheckpointSequence        int32                  `protobuf:"varint,13,opt,name=checkpoint_sequence,json=checkpointSequence,proto3" json:"checkpoint_sequence,omitempty"`                        // sequence number of the latest checkpoint
	CheckpointIntervalSeconds int32                  `protobuf:"varint,14,opt,name=checkpoint_interval_seconds,json=checkpointIntervalSeconds,proto3" json:"checkpoint_interval_seconds,omitempty"` // from leaf's fault_tolerance_config
	RscFpopsEst               float64                `protobuf:"fixed64,15,opt,name=rsc_fpops_est,json=rscFpopsEst,proto3" json:"rsc_fpops_est,omitempty"`                                          // estimated FP ops for this work unit (hours-based buffer sizing)
	ReservedUntilUnix         int64                  `protobuf:"varint,16,opt,name=reserved_until_unix,json=reservedUntilUnix,proto3" json:"reserved_until_unix,omitempty"`                         // head-set lease expiry for this buffered unit
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *WorkUnitAssignment) Reset() {
	*x = WorkUnitAssignment{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkUnitAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkUnitAssignment) ProtoMessage() {}

func (x *WorkUnitAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkUnitAssignment.ProtoReflect.Descriptor instead.
func (*WorkUnitAssignment) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{6}
}

func (x *WorkUnitAssignment) GetWorkUnitId() string {
	if x != nil {
		return x.WorkUnitId
	}
	return ""
}

func (x *WorkUnitAssignment) GetLeafId() string {
	if x != nil {
		return x.LeafId
	}
	return ""
}

func (x *WorkUnitAssignment) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *WorkUnitAssignment) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *WorkUnitAssignment) GetInputDataUrl() string {
	if x != nil {
		return x.InputDataUrl
	}
	return ""
}

func (x *WorkUnitAssignment) GetCodeArtifactUrl() string {
	if x != nil {
		return x.CodeArtifactUrl
	}
	return ""
}

func (x *WorkUnitAssignment) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

func (x *WorkUnitAssignment) GetDeadlineSeconds() int32 {
	if x != nil {
		return x.DeadlineSeconds
	}
	return 0
}

func (x *WorkUnitAssignment) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *WorkUnitAssignment) GetExecutionSpec() *ExecutionSpec {
	if x != nil {
		return x.ExecutionSpec
	}
	return nil
}

func (x *WorkUnitAssignment) GetHasCheckpoint() bool {
	if x != nil {
		return x.HasCheckpoint
	}
	return false
}

func (x *WorkUnitAssignment) GetCheckpointSequence() int32 {
	if x != nil {
		return x.CheckpointSequence
	}
	return 0
}

func (x *WorkUnitAssignment) GetCheckpointIntervalSeconds() int32 {
	if x != nil {
		return x.CheckpointIntervalSeconds
	}
	return 0
}

func (x *WorkUnitAssignment) GetRscFpopsEst() float64 {
	if x != nil {
		return x.RscFpopsEst
	}
	return 0
}

func (x *WorkUnitAssignment) GetReservedUntilUnix() int64 {
	if x != nil {
		return x.ReservedUntilUnix
	}
	return 0
}

type SubmitResultRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkUnitId           string                 `protobuf:"bytes,1,opt,name=work_unit_id,json=workUnitId,proto3" json:"work_unit_id,omitempty"`
	VolunteerId          string                 `protobuf:"bytes,2,opt,name=volunteer_id,json=volunteerId,proto3" json:"volunteer_id,omitempty"`
	PublicKey            []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	OutputData           []byte                 `protobuf:"bytes,4,opt,name=output_data,json=outputData,proto3" json:"output_data,omitempty"`            // inline result (< 100 MB)
	OutputDataUrl        string                 `protobuf:"bytes,5,opt,name=output_data_url,json=outputDataUrl,proto3" json:"output_data_url,omitempty"` // URL if uploaded externally
	OutputChecksumSha256 string                 `protobuf:"bytes,6,opt,name=output_checksum_sha256,json=outputChecksumSha256,proto3" json:"output_checksum_sha256,omitempty"`
	Metadata             *ExecutionMetadata     `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubmitResultRequest) Reset() {
	*x = SubmitResultRequest{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultRequest) ProtoMessage() {}

func (x *SubmitResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitResultRequest) GetWorkUnitId() string {
	if x != nil {
		return x.WorkUnitId
	}
	return ""
}

func (x *SubmitResultRequest) GetVolunteerId() string {
	if x != nil {
		return x.VolunteerId
	}
	return ""
}

func (x *SubmitResultRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SubmitResultRequest) GetOutputData() []byte {
	if x != nil {
		return x.OutputData
	}
	return nil
}

func (x *SubmitResultRequest) GetOutputDataUrl() string {
	if x != nil {
		return x.OutputDataUrl
	}
	return ""
}

func (x *SubmitResultRequest) GetOutputChecksumSha256() string {
	if x != nil {
		return x.OutputChecksumSha256
	}
	return ""
}

func (x *SubmitResultRequest) GetMetadata() *ExecutionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SubmitResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultId      string                 `protobuf:"bytes,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"` // false if duplicate or invalid
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultResponse) Reset() {
	*x = SubmitResultResponse{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultResponse) ProtoMessage() {}

func (x *SubmitResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitResultResponse) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *SubmitResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StartWork marks a buffered (reserved) work unit as run-started: the volunteer
// slot is now executing it. The head performs the QUEUED -> ASSIGNED transition,
// clears the reservation column, writes the active assignment history row, and
// starts the deadline clock (assigned_at = now).
type StartWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkUnitId    string                 `protobuf:"bytes,1,opt,name=work_unit_id,json=workUnitId,proto3" json:"work_unit_id,omitempty"`
	VolunteerId   string                 `protobuf:"bytes,2,opt,name=volunteer_id,json=volunteerId,proto3" json:"volunteer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkRequest) Reset() {
	*x = StartWorkRequest{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkRequest) ProtoMessage() {}

func (x *StartWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkRequest.ProtoReflect.Descriptor instead.
func (*StartWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{9}
}

func (x *StartWorkRequest) GetWorkUnitId() string {
	if x != nil {
		return x.WorkUnitId
	}
	return ""
}

func (x *StartWorkRequest) GetVolunteerId() string {
	if x != nil {
		return x.VolunteerId
	}
	return ""
}

type StartWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`          // true if the unit was run-started for this volunteer
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // diagnostic; on !ok the volunteer should drop the unit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkResponse) Reset() {
	*x = StartWorkResponse{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkResponse) ProtoMessage() {}

func (x *StartWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkResponse.ProtoReflect.Descriptor instead.
func (*StartWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{10}
}

func (x *StartWorkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StartWorkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetWorkUnitStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkUnitId    string                 `protobuf:"bytes,1,opt,name=work_unit_id,json=workUnitId,proto3" json:"work_unit_id,omitempty"`
	VolunteerId   string                 `protobuf:"bytes,2,opt,name=volunteer_id,json=volunteerId,proto3" json:"volunteer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkUnitStatusRequest) Reset() {
	*x = GetWorkUnitStatusRequest{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkUnitStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkUnitStatusRequest) ProtoMessage() {}

func (x *GetWorkUnitStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkUnitStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkUnitStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{11}
}

func (x *GetWorkUnitStatusRequest) GetWorkUnitId() string {
	if x != nil {
		return x.WorkUnitId
	}
	return ""
}

func (x *GetWorkUnitStatusRequest) GetVolunteerId() string {
	if x != nil {
		return x.VolunteerId
	}
	return ""
}

type GetWorkUnitStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkUnitId    string                 `protobuf:"bytes,1,opt,name=work_unit_id,json=workUnitId,proto3" json:"work_unit_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // ASSIGNED, RUNNING, COMPLETED, etc.
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkUnitStatusResponse) Reset() {
	*x = GetWorkUnitStatusResponse{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkUnitStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkUnitStatusResponse) ProtoMessage() {}

func (x *GetWorkUnitStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkUnitStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWorkUnitStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{12}
}

func (x *GetWorkUnitStatusResponse) GetWorkUnitId() string {
	if x != nil {
		return x.WorkUnitId
	}
	return ""
}

func (x *GetWorkUnitStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetWorkUnitStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SaveCheckpointRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkUnitId         string                 `protobuf:"bytes,1,opt,name=work_unit_id,json=workUnitId,proto3" json:"work_unit_id,omitempty"`
	VolunteerId        string                 `protobuf:"bytes,2,opt,name=volunteer_id,json=volunteerId,proto3" json:"volunteer_id,omitempty"`
	PublicKey          string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	CheckpointData     []byte                 `protobuf:"bytes,4,opt,name=checkpoint_data,json=checkpointData,proto3" json:"checkpoint_data,omitempty"`              // opaque blob, max size configurable (default 100 MB)
	CheckpointSequence int32                  `protobuf:"varint,5,opt,name=checkpoint_sequence,json=checkpointSequence,proto3" json:"checkpoint_sequence,omitempty"` // must be > current sequence for this work unit
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SaveCheckpointRequest) Reset() {
	*x = SaveCheckpointRequest{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCheckpointRequest) ProtoMessage() {}

func (x *SaveCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCheckpointRequest.ProtoReflect.Descriptor instead.
func (*SaveCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{13}
}

func (x *SaveCheckpointRequest) GetWorkUnitId() string {
	if x != nil {
		return x.WorkUnitId
	}
	return ""
}

func (x *SaveCheckpointRequest) GetVolunteerId() string {
	if x != nil {
		return x.VolunteerId
	}
	return ""
}

func (x *SaveCheckpointRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SaveCheckpointRequest) GetCheckpointData() []byte {
	if x != nil {
		return x.CheckpointData
	}
	return nil
}

func (x *SaveCheckpointRequest) GetCheckpointSequence() int32 {
	if x != nil {
		return x.CheckpointSequence
	}
	return 0
}

type SaveCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCheckpointResponse) Reset() {
	*x = SaveCheckpointResponse{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCheckpointResponse) ProtoMessage() {}

func (x *SaveCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCheckpointResponse.ProtoReflect.Descriptor instead.
func (*SaveCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{14}
}

func (x *SaveCheckpointResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SaveCheckpointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkUnitId    string                 `protobuf:"bytes,1,opt,name=work_unit_id,json=workUnitId,proto3" json:"work_unit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointRequest) Reset() {
	*x = GetCheckpointRequest{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointRequest) ProtoMessage() {}

func (x *GetCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointRequest.ProtoReflect.Descriptor instead.
func (*GetCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{15}
}

func (x *GetCheckpointRequest) GetWorkUnitId() string {
	if x != nil {
		return x.WorkUnitId
	}
	return ""
}

type GetCheckpointResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	HasCheckpoint        bool                   `protobuf:"varint,1,opt,name=has_checkpoint,json=hasCheckpoint,proto3" json:"has_checkpoint,omitempty"`
	CheckpointData       []byte                 `protobuf:"bytes,2,opt,name=checkpoint_data,json=checkpointData,proto3" json:"checkpoint_data,omitempty"`
	CheckpointSequence   int32                  `protobuf:"varint,3,opt,name=checkpoint_sequence,json=checkpointSequence,proto3" json:"checkpoint_sequence,omitempty"`
	CreatedByVolunteerId string                 `protobuf:"bytes,4,opt,name=created_by_volunteer_id,json=createdByVolunteerId,proto3" json:"created_by_volunteer_id,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC 3339
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetCheckpointResponse) Reset() {
	*x = GetCheckpointResponse{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointResponse) ProtoMessage() {}

func (x *GetCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointResponse.ProtoReflect.Descriptor instead.
func (*GetCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{16}
}

func (x *GetCheckpointResponse) GetHasCheckpoint() bool {
	if x != nil {
		return x.HasCheckpoint
	}
	return false
}

func (x *GetCheckpointResponse) GetCheckpointData() []byte {
	if x != nil {
		return x.CheckpointData
	}
	return nil
}

func (x *GetCheckpointResponse) GetCheckpointSequence() int32 {
	if x != nil {
		return x.CheckpointSequence
	}
	return 0
}

func (x *GetCheckpointResponse) GetCreatedByVolunteerId() string {
	if x != nil {
		return x.CreatedByVolunteerId
	}
	return ""
}

func (x *GetCheckpointResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type HardwareCapabilities struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuCores         int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuModel         string                 `protobuf:"bytes,2,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	MaxCpuCores      int32                  `protobuf:"varint,3,opt,name=max_cpu_cores,json=maxCpuCores,proto3" json:"max_cpu_cores,omitempty"`
	MemoryTotalMb    int32                  `protobuf:"varint,4,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	MaxMemoryMb      int32                  `protobuf:"varint,5,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`
	DiskAvailableMb  int64                  `protobuf:"varint,6,opt,name=disk_available_mb,json=diskAvailableMb,proto3" json:"disk_available_mb,omitempty"`
	MaxDiskMb        int64                  `protobuf:"varint,7,opt,name=max_disk_mb,json=maxDiskMb,proto3" json:"max_disk_mb,omitempty"`
	MaxBandwidthMbps int32                  `protobuf:"varint,8,opt,name=max_bandwidth_mbps,json=maxBandwidthMbps,proto3" json:"max_bandwidth_mbps,omitempty"`
	Gpus             []*GpuInfo             `protobuf:"bytes,9,rep,name=gpus,proto3" json:"gpus,omitempty"`
	BenchmarkFpops   float64                `protobuf:"fixed64,10,opt,name=benchmark_fpops,json=benchmarkFpops,proto3" json:"benchmark_fpops,omitempty"` // CPU benchmark: floating-point ops per second
	// Hardware-class inputs for Homogeneous Redundancy (HR): the head derives an HR
	// class string from these so all redundant copies of a work unit run on the same
	// class of machine and their floating-point results are bit-comparable.
	Os            string `protobuf:"bytes,11,opt,name=os,proto3" json:"os,omitempty"`                                // GOOS: linux, darwin, windows
	CpuArch       string `protobuf:"bytes,12,opt,name=cpu_arch,json=cpuArch,proto3" json:"cpu_arch,omitempty"`       // GOARCH: amd64, arm64
	CpuVendor     string `protobuf:"bytes,13,opt,name=cpu_vendor,json=cpuVendor,proto3" json:"cpu_vendor,omitempty"` // GenuineIntel, AuthenticAMD, Apple, ... ("" if unknown)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareCapabilities) Reset() {
	*x = HardwareCapabilities{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareCapabilities) ProtoMessage() {}

func (x *HardwareCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareCapabilities.ProtoReflect.Descriptor instead.
func (*HardwareCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{17}
}

func (x *HardwareCapabilities) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HardwareCapabilities) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *HardwareCapabilities) GetMaxCpuCores() int32 {
	if x != nil {
		return x.MaxCpuCores
	}
	return 0
}

func (x *HardwareCapabilities) GetMemoryTotalMb() int32 {
	if x != nil {
		return x.MemoryTotalMb
	}
	return 0
}

func (x *HardwareCapabilities) GetMaxMemoryMb() int32 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

func (x *HardwareCapabilities) GetDiskAvailableMb() int64 {
	if x != nil {
		return x.DiskAvailableMb
	}
	return 0
}

func (x *HardwareCapabilities) GetMaxDiskMb() int64 {
	if x != nil {
		return x.MaxDiskMb
	}
	return 0
}

func (x *HardwareCapabilities) GetMaxBandwidthMbps() int32 {
	if x != nil {
		return x.MaxBandwidthMbps
	}
	return 0
}

func (x *HardwareCapabilities) GetGpus() []*GpuInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *HardwareCapabilities) GetBenchmarkFpops() float64 {
	if x != nil {
		return x.BenchmarkFpops
	}
	return 0
}

func (x *HardwareCapabilities) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HardwareCapabilities) GetCpuArch() string {
	if x != nil {
		return x.CpuArch
	}
	return ""
}

func (x *HardwareCapabilities) GetCpuVendor() string {
	if x != nil {
		return x.CpuVendor
	}
	return ""
}

type GpuInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Vendor            string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"` // nvidia, amd
	VramMb            int32                  `protobuf:"varint,3,opt,name=vram_mb,json=vramMb,proto3" json:"vram_mb,omitempty"`
	MaxVramPct        int32                  `protobuf:"varint,4,opt,name=max_vram_pct,json=maxVramPct,proto3" json:"max_vram_pct,omitempty"`
	ComputeCapability string                 `protobuf:"bytes,5,opt,name=compute_capability,json=computeCapability,proto3" json:"compute_capability,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GpuInfo) Reset() {
	*x = GpuInfo{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuInfo) ProtoMessage() {}

func (x *GpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuInfo.ProtoReflect.Descriptor instead.
func (*GpuInfo) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{18}
}

func (x *GpuInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GpuInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GpuInfo) GetVramMb() int32 {
	if x != nil {
		return x.VramMb
	}
	return 0
}

func (x *GpuInfo) GetMaxVramPct() int32 {
	if x != nil {
		return x.MaxVramPct
	}
	return 0
}

func (x *GpuInfo) GetComputeCapability() string {
	if x != nil {
		return x.ComputeCapability
	}
	return ""
}

type ExecutionMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WallClockSeconds int64                  `protobuf:"varint,1,opt,name=wall_clock_seconds,json=wallClockSeconds,proto3" json:"wall_clock_seconds,omitempty"`
	CpuSecondsUser   float64                `protobuf:"fixed64,2,opt,name=cpu_seconds_user,json=cpuSecondsUser,proto3" json:"cpu_seconds_user,omitempty"`
	CpuSecondsSystem float64                `protobuf:"fixed64,3,opt,name=cpu_seconds_system,json=cpuSecondsSystem,proto3" json:"cpu_seconds_system,omitempty"`
	CpuCoresUsed     int32                  `protobuf:"varint,4,opt,name=cpu_cores_used,json=cpuCoresUsed,proto3" json:"cpu_cores_used,omitempty"`
	GpuSeconds       float64                `protobuf:"fixed64,5,opt,name=gpu_seconds,json=gpuSeconds,proto3" json:"gpu_seconds,omitempty"`
	GpuModel         string                 `protobuf:"bytes,6,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`
	GpuVramUsedMb    int32                  `protobuf:"varint,7,opt,name=gpu_vram_used_mb,json=gpuVramUsedMb,proto3" json:"gpu_vram_used_mb,omitempty"`
	PeakMemoryMb     int32                  `protobuf:"varint,8,opt,name=peak_memory_mb,json=peakMemoryMb,proto3" json:"peak_memory_mb,omitempty"`
	DiskReadMb       int64                  `protobuf:"varint,9,opt,name=disk_read_mb,json=diskReadMb,proto3" json:"disk_read_mb,omitempty"`
	DiskWriteMb      int64                  `protobuf:"varint,10,opt,name=disk_write_mb,json=diskWriteMb,proto3" json:"disk_write_mb,omitempty"`
	NetworkRxMb      int64                  `protobuf:"varint,11,opt,name=network_rx_mb,json=networkRxMb,proto3" json:"network_rx_mb,omitempty"`
	NetworkTxMb      int64                  `protobuf:"varint,12,opt,name=network_tx_mb,json=networkTxMb,proto3" json:"network_tx_mb,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionMetadata) Reset() {
	*x = ExecutionMetadata{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionMetadata) ProtoMessage() {}

func (x *ExecutionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionMetadata.ProtoReflect.Descriptor instead.
func (*ExecutionMetadata) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{19}
}

func (x *ExecutionMetadata) GetWallClockSeconds() int64 {
	if x != nil {
		return x.WallClockSeconds
	}
	return 0
}

func (x *ExecutionMetadata) GetCpuSecondsUser() float64 {
	if x != nil {
		return x.CpuSecondsUser
	}
	return 0
}

func (x *ExecutionMetadata) GetCpuSecondsSystem() float64 {
	if x != nil {
		return x.CpuSecondsSystem
	}
	return 0
}

func (x *ExecutionMetadata) GetCpuCoresUsed() int32 {
	if x != nil {
		return x.CpuCoresUsed
	}
	return 0
}

func (x *ExecutionMetadata) GetGpuSeconds() float64 {
	if x != nil {
		return x.GpuSeconds
	}
	return 0
}

func (x *ExecutionMetadata) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *ExecutionMetadata) GetGpuVramUsedMb() int32 {
	if x != nil {
		return x.GpuVramUsedMb
	}
	return 0
}

func (x *ExecutionMetadata) GetPeakMemoryMb() int32 {
	if x != nil {
		return x.PeakMemoryMb
	}
	return 0
}

func (x *ExecutionMetadata) GetDiskReadMb() int64 {
	if x != nil {
		return x.DiskReadMb
	}
	return 0
}

func (x *ExecutionMetadata) GetDiskWriteMb() int64 {
	if x != nil {
		return x.DiskWriteMb
	}
	return 0
}

func (x *ExecutionMetadata) GetNetworkRxMb() int64 {
	if x != nil {
		return x.NetworkRxMb
	}
	return 0
}

func (x *ExecutionMetadata) GetNetworkTxMb() int64 {
	if x != nil {
		return x.NetworkTxMb
	}
	return 0
}

type ExecutionSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binaries      map[string]string      `protobuf:"bytes,1,rep,name=binaries,proto3" json:"binaries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // platform -> URL (native)
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`                                                                                 // OCI image ref (container)
	GpuRequired   bool                   `protobuf:"varint,3,opt,name=gpu_required,json=gpuRequired,proto3" json:"gpu_required,omitempty"`
	GpuType       string                 `protobuf:"bytes,4,opt,name=gpu_type,json=gpuType,proto3" json:"gpu_type,omitempty"`
	MaxMemoryMb   int32                  `protobuf:"varint,5,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`
	MaxDiskMb     int32                  `protobuf:"varint,6,opt,name=max_disk_mb,json=maxDiskMb,proto3" json:"max_disk_mb,omitempty"`
	NetworkAccess bool                   `protobuf:"varint,7,opt,name=network_access,json=networkAccess,proto3" json:"network_access,omitempty"`
	// binary_checksums maps each platform key in `binaries` to the lowercase hex
	// SHA-256 of the artifact at that URL. Volunteers verify the downloaded bytes
	// against this digest before execution (integrity / anti-tamper). For NATIVE
	// runtime leafs a checksum is REQUIRED for every binaries entry; for
	// wasm/viz/container it is optional but verified when present.
	BinaryChecksums map[string]string `protobuf:"bytes,8,rep,name=binary_checksums,json=binaryChecksums,proto3" json:"binary_checksums,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionSpec) Reset() {
	*x = ExecutionSpec{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionSpec) ProtoMessage() {}

func (x *ExecutionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionSpec.ProtoReflect.Descriptor instead.
func (*ExecutionSpec) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{20}
}

func (x *ExecutionSpec) GetBinaries() map[string]string {
	if x != nil {
		return x.Binaries
	}
	return nil
}

func (x *ExecutionSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ExecutionSpec) GetGpuRequired() bool {
	if x != nil {
		return x.GpuRequired
	}
	return false
}

func (x *ExecutionSpec) GetGpuType() string {
	if x != nil {
		return x.GpuType
	}
	return ""
}

func (x *ExecutionSpec) GetMaxMemoryMb() int32 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

func (x *ExecutionSpec) GetMaxDiskMb() int32 {
	if x != nil {
		return x.MaxDiskMb
	}
	return 0
}

func (x *ExecutionSpec) GetNetworkAccess() bool {
	if x != nil {
		return x.NetworkAccess
	}
	return false
}

func (x *ExecutionSpec) GetBinaryChecksums() map[string]string {
	if x != nil {
		return x.BinaryChecksums
	}
	return nil
}

type GetHeadInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeadInfoRequest) Reset() {
	*x = GetHeadInfoRequest{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadInfoRequest) ProtoMessage() {}

func (x *GetHeadInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadInfoRequest.ProtoReflect.Descriptor instead.
func (*GetHeadInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{21}
}

type GetHeadInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url                string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Leafs              []*LeafInfo            `protobuf:"bytes,4,rep,name=leafs,proto3" json:"leafs,omitempty"`
	DefaultLeafWeights map[string]int32       `protobuf:"bytes,5,rep,name=default_leaf_weights,json=defaultLeafWeights,proto3" json:"default_leaf_weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetHeadInfoResponse) Reset() {
	*x = GetHeadInfoResponse{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadInfoResponse) ProtoMessage() {}

func (x *GetHeadInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadInfoResponse.ProtoReflect.Descriptor instead.
func (*GetHeadInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{22}
}

func (x *GetHeadInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetHeadInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetHeadInfoResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetHeadInfoResponse) GetLeafs() []*LeafInfo {
	if x != nil {
		return x.Leafs
	}
	return nil
}

func (x *GetHeadInfoResponse) GetDefaultLeafWeights() map[string]int32 {
	if x != nil {
		return x.DefaultLeafWeights
	}
	return nil
}

type LeafInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug             string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ResearchArea     []string               `protobuf:"bytes,5,rep,name=research_area,json=researchArea,proto3" json:"research_area,omitempty"`
	TaskPattern      string                 `protobuf:"bytes,6,opt,name=task_pattern,json=taskPattern,proto3" json:"task_pattern,omitempty"`
	State            string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	QueuedWorkUnits  int32                  `protobuf:"varint,8,opt,name=queued_work_units,json=queuedWorkUnits,proto3" json:"queued_work_units,omitempty"`
	ActiveVolunteers int32                  `protobuf:"varint,9,opt,name=active_volunteers,json=activeVolunteers,proto3" json:"active_volunteers,omitempty"`
	ExecutionSpec    *ExecutionSpec         `protobuf:"bytes,10,opt,name=execution_spec,json=executionSpec,proto3" json:"execution_spec,omitempty"` // runtime badges for desktop/browser clients
	// Benchmark-independent per-leaf duration estimate (seconds) used by the
	// volunteer for duration-aware work batching: it sizes the first batch request
	// to fill work_buffer_hours instead of idling at the flat per-request ceiling.
	EstimatedDurationSeconds float64 `protobuf:"fixed64,11,opt,name=estimated_duration_seconds,json=estimatedDurationSeconds,proto3" json:"estimated_duration_seconds,omitempty"`
	// Distinct active MACHINES on the leaf. A volunteer running one identity key on
	// N machines is 1 active_volunteer but N active_hosts (account<->host split).
	ActiveHosts   int32 `protobuf:"varint,12,opt,name=active_hosts,json=activeHosts,proto3" json:"active_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeafInfo) Reset() {
	*x = LeafInfo{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeafInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafInfo) ProtoMessage() {}

func (x *LeafInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafInfo.ProtoReflect.Descriptor instead.
func (*LeafInfo) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{23}
}

func (x *LeafInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LeafInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *LeafInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeafInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LeafInfo) GetResearchArea() []string {
	if x != nil {
		return x.ResearchArea
	}
	return nil
}

func (x *LeafInfo) GetTaskPattern() string {
	if x != nil {
		return x.TaskPattern
	}
	return ""
}

func (x *LeafInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *LeafInfo) GetQueuedWorkUnits() int32 {
	if x != nil {
		return x.QueuedWorkUnits
	}
	return 0
}

func (x *LeafInfo) GetActiveVolunteers() int32 {
	if x != nil {
		return x.ActiveVolunteers
	}
	return 0
}

func (x *LeafInfo) GetExecutionSpec() *ExecutionSpec {
	if x != nil {
		return x.ExecutionSpec
	}
	return nil
}

func (x *LeafInfo) GetEstimatedDurationSeconds() float64 {
	if x != nil {
		return x.EstimatedDurationSeconds
	}
	return 0
}

func (x *LeafInfo) GetActiveHosts() int32 {
	if x != nil {
		return x.ActiveHosts
	}
	return 0
}

type AbandonWorkUnitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkUnitId    string                 `protobuf:"bytes,1,opt,name=work_unit_id,json=workUnitId,proto3" json:"work_unit_id,omitempty"`
	VolunteerId   string                 `protobuf:"bytes,2,opt,name=volunteer_id,json=volunteerId,proto3" json:"volunteer_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // e.g., "prepare failed: no binary for platform"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonWorkUnitRequest) Reset() {
	*x = AbandonWorkUnitRequest{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonWorkUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonWorkUnitRequest) ProtoMessage() {}

func (x *AbandonWorkUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonWorkUnitRequest.ProtoReflect.Descriptor instead.
func (*AbandonWorkUnitRequest) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{24}
}

func (x *AbandonWorkUnitRequest) GetWorkUnitId() string {
	if x != nil {
		return x.WorkUnitId
	}
	return ""
}

func (x *AbandonWorkUnitRequest) GetVolunteerId() string {
	if x != nil {
		return x.VolunteerId
	}
	return ""
}

func (x *AbandonWorkUnitRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *AbandonWorkUnitRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbandonWorkUnitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requeued      bool                   `protobuf:"varint,1,opt,name=requeued,proto3" json:"requeued,omitempty"` // true if work unit was put back in the queue
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonWorkUnitResponse) Reset() {
	*x = AbandonWorkUnitResponse{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonWorkUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonWorkUnitResponse) ProtoMessage() {}

func (x *AbandonWorkUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonWorkUnitResponse.ProtoReflect.Descriptor instead.
func (*AbandonWorkUnitResponse) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{25}
}

func (x *AbandonWorkUnitResponse) GetRequeued() bool {
	if x != nil {
		return x.Requeued
	}
	return false
}

func (x *AbandonWorkUnitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetMyContributionRequest carries no identity field on purpose: the head derives
// the caller from the verified request signature, so the request body is empty.
type GetMyContributionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyContributionRequest) Reset() {
	*x = GetMyContributionRequest{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyContributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyContributionRequest) ProtoMessage() {}

func (x *GetMyContributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyContributionRequest.ProtoReflect.Descriptor instead.
func (*GetMyContributionRequest) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{26}
}

type GetMyContributionResponse struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	VolunteerId    string                      `protobuf:"bytes,1,opt,name=volunteer_id,json=volunteerId,proto3" json:"volunteer_id,omitempty"`            // resolved ACCOUNT id (informational)
	TotalCredit    float64                     `protobuf:"fixed64,2,opt,name=total_credit,json=totalCredit,proto3" json:"total_credit,omitempty"`          // sum of all credit across every leaf/machine
	ByLeaf         []*LeafContribution         `protobuf:"bytes,3,rep,name=by_leaf,json=byLeaf,proto3" json:"by_leaf,omitempty"`                           // per-leaf credit + resource usage
	ByResourceType []*ResourceTypeContribution `protobuf:"bytes,4,rep,name=by_resource_type,json=byResourceType,proto3" json:"by_resource_type,omitempty"` // cpu_only / gpu split
	Daily          []*DailyContribution        `protobuf:"bytes,5,rep,name=daily,proto3" json:"daily,omitempty"`                                           // last 30 days
	Weekly         []*WeeklyContribution       `protobuf:"bytes,6,rep,name=weekly,proto3" json:"weekly,omitempty"`                                         // last 12 weeks
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMyContributionResponse) Reset() {
	*x = GetMyContributionResponse{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyContributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyContributionResponse) ProtoMessage() {}

func (x *GetMyContributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyContributionResponse.ProtoReflect.Descriptor instead.
func (*GetMyContributionResponse) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{27}
}

func (x *GetMyContributionResponse) GetVolunteerId() string {
	if x != nil {
		return x.VolunteerId
	}
	return ""
}

func (x *GetMyContributionResponse) GetTotalCredit() float64 {
	if x != nil {
		return x.TotalCredit
	}
	return 0
}

func (x *GetMyContributionResponse) GetByLeaf() []*LeafContribution {
	if x != nil {
		return x.ByLeaf
	}
	return nil
}

func (x *GetMyContributionResponse) GetByResourceType() []*ResourceTypeContribution {
	if x != nil {
		return x.ByResourceType
	}
	return nil
}

func (x *GetMyContributionResponse) GetDaily() []*DailyContribution {
	if x != nil {
		return x.Daily
	}
	return nil
}

func (x *GetMyContributionResponse) GetWeekly() []*WeeklyContribution {
	if x != nil {
		return x.Weekly
	}
	return nil
}

type LeafContribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeafId        string                 `protobuf:"bytes,1,opt,name=leaf_id,json=leafId,proto3" json:"leaf_id,omitempty"`
	LeafName      string                 `protobuf:"bytes,2,opt,name=leaf_name,json=leafName,proto3" json:"leaf_name,omitempty"`
	Credit        float64                `protobuf:"fixed64,3,opt,name=credit,proto3" json:"credit,omitempty"`
	WorkUnits     int32                  `protobuf:"varint,4,opt,name=work_units,json=workUnits,proto3" json:"work_units,omitempty"`
	CpuSeconds    float64                `protobuf:"fixed64,5,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`
	GpuSeconds    float64                `protobuf:"fixed64,6,opt,name=gpu_seconds,json=gpuSeconds,proto3" json:"gpu_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeafContribution) Reset() {
	*x = LeafContribution{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeafContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafContribution) ProtoMessage() {}

func (x *LeafContribution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafContribution.ProtoReflect.Descriptor instead.
func (*LeafContribution) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{28}
}

func (x *LeafContribution) GetLeafId() string {
	if x != nil {
		return x.LeafId
	}
	return ""
}

func (x *LeafContribution) GetLeafName() string {
	if x != nil {
		return x.LeafName
	}
	return ""
}

func (x *LeafContribution) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *LeafContribution) GetWorkUnits() int32 {
	if x != nil {
		return x.WorkUnits
	}
	return 0
}

func (x *LeafContribution) GetCpuSeconds() float64 {
	if x != nil {
		return x.CpuSeconds
	}
	return 0
}

func (x *LeafContribution) GetGpuSeconds() float64 {
	if x != nil {
		return x.GpuSeconds
	}
	return 0
}

type ResourceTypeContribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // "cpu_only" or "gpu"
	Credit        float64                `protobuf:"fixed64,2,opt,name=credit,proto3" json:"credit,omitempty"`
	WorkUnits     int32                  `protobuf:"varint,3,opt,name=work_units,json=workUnits,proto3" json:"work_units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceTypeContribution) Reset() {
	*x = ResourceTypeContribution{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceTypeContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTypeContribution) ProtoMessage() {}

func (x *ResourceTypeContribution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTypeContribution.ProtoReflect.Descriptor instead.
func (*ResourceTypeContribution) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{29}
}

func (x *ResourceTypeContribution) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceTypeContribution) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *ResourceTypeContribution) GetWorkUnits() int32 {
	if x != nil {
		return x.WorkUnits
	}
	return 0
}

type DailyContribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD (UTC day)
	Credit        float64                `protobuf:"fixed64,2,opt,name=credit,proto3" json:"credit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyContribution) Reset() {
	*x = DailyContribution{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyContribution) ProtoMessage() {}

func (x *DailyContribution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyContribution.ProtoReflect.Descriptor instead.
func (*DailyContribution) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{30}
}

func (x *DailyContribution) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyContribution) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

type WeeklyContribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekStart     string                 `protobuf:"bytes,1,opt,name=week_start,json=weekStart,proto3" json:"week_start,omitempty"` // YYYY-MM-DD (week start, UTC)
	Credit        float64                `protobuf:"fixed64,2,opt,name=credit,proto3" json:"credit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklyContribution) Reset() {
	*x = WeeklyContribution{}
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyContribution) ProtoMessage() {}

func (x *WeeklyContribution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lettuce_v1_volunteer_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyContribution.ProtoReflect.Descriptor instead.
func (*WeeklyContribution) Descriptor() ([]byte, []int) {
	return file_proto_lettuce_v1_volunteer_proto_rawDescGZIP(), []int{31}
}

func (x *WeeklyContribution) GetWeekStart() string {
	if x != nil {
		return x.WeekStart
	}
	return ""
}

func (x *WeeklyContribution) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

var File_proto_lettuce_v1_volunteer_proto protoreflect.FileDescriptor

const file_proto_lettuce_v1_volunteer_proto_rawDesc = "" +
	"\n" +
	" proto/lettuce/v1/volunteer.proto\x12\x14lettuce.volunteer.v1\"\x18\n" +
	"\x16GetServerStatusRequest\"\x9b\x01\n" +
	"\x17GetServerStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0fdatabase_status\x18\x04 \x01(\tR\x0edatabaseStatus\"\x95\x02\n" +
	"\x18RegisterVolunteerRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12F\n" +
	"\bhardware\x18\x03 \x01(\v2*.lettuce.volunteer.v1.HardwareCapabilitiesR\bhardware\x12-\n" +
	"\x12available_runtimes\x18\x04 \x03(\tR\x11availableRuntimes\x12'\n" +
	"\x0fscheduling_mode\x18\x05 \x01(\tR\x0eschedulingMode\x12\x17\n" +
	"\ahost_id\x18\x06 \x01(\tR\x06hostId\"^\n" +
	"\x19RegisterVolunteerResponse\x12!\n" +
	"\fvolunteer_id\x18\x01 \x01(\tR\vvolunteerId\x12\x1e\n" +
	"\n" +
	"registered\x18\x02 \x01(\bR\n" +
	"registered\"\xe7\x02\n" +
	"\x16RequestWorkUnitRequest\x12!\n" +
	"\fvolunteer_id\x18\x01 \x01(\tR\vvolunteerId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12W\n" +
	"\x11current_available\x18\x03 \x01(\v2*.lettuce.volunteer.v1.HardwareCapabilitiesR\x10currentAvailable\x12\x19\n" +
	"\bleaf_ids\x18\x04 \x03(\tR\aleafIds\x12(\n" +
	"\x10blocked_leaf_ids\x18\x05 \x03(\tR\x0eblockedLeafIds\x12'\n" +
	"\x0fmax_assignments\x18\x06 \x01(\x05R\x0emaxAssignments\x12+\n" +
	"\x12held_work_unit_ids\x18\a \x03(\tR\x0fheldWorkUnitIds\x12\x17\n" +
	"\ahost_id\x18\b \x01(\tR\x06hostId\"\x95\x01\n" +
	"\x17RequestWorkUnitResponse\x12J\n" +
	"\vassignments\x18\x01 \x03(\v2(.lettuce.volunteer.v1.WorkUnitAssignmentR\vassignments\x12.\n" +
	"\x13retry_after_seconds\x18\x02 \x01(\x05R\x11retryAfterSeconds\"\xfa\x05\n" +
	"\x12WorkUnitAssignment\x12 \n" +
	"\fwork_unit_id\x18\x01 \x01(\tR\n" +
	"workUnitId\x12\x17\n" +
	"\aleaf_id\x18\x02 \x01(\tR\x06leafId\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12\x1d\n" +
	"\n" +
	"input_data\x18\x04 \x01(\fR\tinputData\x12$\n" +
	"\x0einput_data_url\x18\x05 \x01(\tR\finputDataUrl\x12*\n" +
	"\x11code_artifact_url\x18\x06 \x01(\tR\x0fcodeArtifactUrl\x12'\n" +
	"\x0fparameters_json\x18\a \x01(\tR\x0eparametersJson\x12)\n" +
	"\x10deadline_seconds\x18\b \x01(\x05R\x0fdeadlineSeconds\x12P\n" +
	"\benv_vars\x18\n" +
	" \x03(\v25.lettuce.volunteer.v1.WorkUnitAssignment.EnvVarsEntryR\aenvVars\x12J\n" +
	"\x0eexecution_spec\x18\v \x01(\v2#.lettuce.volunteer.v1.ExecutionSpecR\rexecutionSpec\x12%\n" +
	"\x0ehas_checkpoint\x18\f \x01(\bR\rhasCheckpoint\x12/\n" +
	"\x13checkpoint_sequence\x18\r \x01(\x05R\x12checkpointSequence\x12>\n" +
	"\x1bcheckpoint_interval_seconds\x18\x0e \x01(\x05R\x19checkpointIntervalSeconds\x12\"\n" +
	"\rrsc_fpops_est\x18\x0f \x01(\x01R\vrscFpopsEst\x12.\n" +
	"\x13reserved_until_unix\x18\x10 \x01(\x03R\x11reservedUntilUnix\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\t\x10\n" +
	"\"\xbd\x02\n" +
	"\x13SubmitResultRequest\x12 \n" +
	"\fwork_unit_id\x18\x01 \x01(\tR\n" +
	"workUnitId\x12!\n" +
	"\fvolunteer_id\x18\x02 \x01(\tR\vvolunteerId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\voutput_data\x18\x04 \x01(\fR\n" +
	"outputData\x12&\n" +
	"\x0foutput_data_url\x18\x05 \x01(\tR\routputDataUrl\x124\n" +
	"\x16output_checksum_sha256\x18\x06 \x01(\tR\x14outputChecksumSha256\x12C\n" +
	"\bmetadata\x18\a \x01(\v2'.lettuce.volunteer.v1.ExecutionMetadataR\bmetadata\"i\n" +
	"\x14SubmitResultResponse\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\tR\bresultId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"W\n" +
	"\x10StartWorkRequest\x12 \n" +
	"\fwork_unit_id\x18\x01 \x01(\tR\n" +
	"workUnitId\x12!\n" +
	"\fvolunteer_id\x18\x02 \x01(\tR\vvolunteerId\"=\n" +
	"\x11StartWorkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\x18GetWorkUnitStatusRequest\x12 \n" +
	"\fwork_unit_id\x18\x01 \x01(\tR\n" +
	"workUnitId\x12!\n" +
	"\fvolunteer_id\x18\x02 \x01(\tR\vvolunteerId\"m\n" +
	"\x19GetWorkUnitStatusResponse\x12 \n" +
	"\fwork_unit_id\x18\x01 \x01(\tR\n" +
	"workUnitId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd5\x01\n" +
	"\x15SaveCheckpointRequest\x12 \n" +
	"\fwork_unit_id\x18\x01 \x01(\tR\n" +
	"workUnitId\x12!\n" +
	"\fvolunteer_id\x18\x02 \x01(\tR\vvolunteerId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12'\n" +
	"\x0fcheckpoint_data\x18\x04 \x01(\fR\x0echeckpointData\x12/\n" +
	"\x13checkpoint_sequence\x18\x05 \x01(\x05R\x12checkpointSequence\"N\n" +
	"\x16SaveCheckpointResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x14GetCheckpointRequest\x12 \n" +
	"\fwork_unit_id\x18\x01 \x01(\tR\n" +
	"workUnitId\"\xee\x01\n" +
	"\x15GetCheckpointResponse\x12%\n" +
	"\x0ehas_checkpoint\x18\x01 \x01(\bR\rhasCheckpoint\x12'\n" +
	"\x0fcheckpoint_data\x18\x02 \x01(\fR\x0echeckpointData\x12/\n" +
	"\x13checkpoint_sequence\x18\x03 \x01(\x05R\x12checkpointSequence\x125\n" +
	"\x17created_by_volunteer_id\x18\x04 \x01(\tR\x14createdByVolunteerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xe0\x03\n" +
	"\x14HardwareCapabilities\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tcpu_model\x18\x02 \x01(\tR\bcpuModel\x12\"\n" +
	"\rmax_cpu_cores\x18\x03 \x01(\x05R\vmaxCpuCores\x12&\n" +
	"\x0fmemory_total_mb\x18\x04 \x01(\x05R\rmemoryTotalMb\x12\"\n" +
	"\rmax_memory_mb\x18\x05 \x01(\x05R\vmaxMemoryMb\x12*\n" +
	"\x11disk_available_mb\x18\x06 \x01(\x03R\x0fdiskAvailableMb\x12\x1e\n" +
	"\vmax_disk_mb\x18\a \x01(\x03R\tmaxDiskMb\x12,\n" +
	"\x12max_bandwidth_mbps\x18\b \x01(\x05R\x10maxBandwidthMbps\x121\n" +
	"\x04gpus\x18\t \x03(\v2\x1d.lettuce.volunteer.v1.GpuInfoR\x04gpus\x12'\n" +
	"\x0fbenchmark_fpops\x18\n" +
	" \x01(\x01R\x0ebenchmarkFpops\x12\x0e\n" +
	"\x02os\x18\v \x01(\tR\x02os\x12\x19\n" +
	"\bcpu_arch\x18\f \x01(\tR\acpuArch\x12\x1d\n" +
	"\n" +
	"cpu_vendor\x18\r \x01(\tR\tcpuVendor\"\xa1\x01\n" +
	"\aGpuInfo\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x17\n" +
	"\avram_mb\x18\x03 \x01(\x05R\x06vramMb\x12 \n" +
	"\fmax_vram_pct\x18\x04 \x01(\x05R\n" +
	"maxVramPct\x12-\n" +
	"\x12compute_capability\x18\x05 \x01(\tR\x11computeCapability\"\xda\x03\n" +
	"\x11ExecutionMetadata\x12,\n" +
	"\x12wall_clock_seconds\x18\x01 \x01(\x03R\x10wallClockSeconds\x12(\n" +
	"\x10cpu_seconds_user\x18\x02 \x01(\x01R\x0ecpuSecondsUser\x12,\n" +
	"\x12cpu_seconds_system\x18\x03 \x01(\x01R\x10cpuSecondsSystem\x12$\n" +
	"\x0ecpu_cores_used\x18\x04 \x01(\x05R\fcpuCoresUsed\x12\x1f\n" +
	"\vgpu_seconds\x18\x05 \x01(\x01R\n" +
	"gpuSeconds\x12\x1b\n" +
	"\tgpu_model\x18\x06 \x01(\tR\bgpuModel\x12'\n" +
	"\x10gpu_vram_used_mb\x18\a \x01(\x05R\rgpuVramUsedMb\x12$\n" +
	"\x0epeak_memory_mb\x18\b \x01(\x05R\fpeakMemoryMb\x12 \n" +
	"\fdisk_read_mb\x18\t \x01(\x03R\n" +
	"diskReadMb\x12\"\n" +
	"\rdisk_write_mb\x18\n" +
	" \x01(\x03R\vdiskWriteMb\x12\"\n" +
	"\rnetwork_rx_mb\x18\v \x01(\x03R\vnetworkRxMb\x12\"\n" +
	"\rnetwork_tx_mb\x18\f \x01(\x03R\vnetworkTxMb\"\x83\x04\n" +
	"\rExecutionSpec\x12M\n" +
	"\bbinaries\x18\x01 \x03(\v21.lettuce.volunteer.v1.ExecutionSpec.BinariesEntryR\bbinaries\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12!\n" +
	"\fgpu_required\x18\x03 \x01(\bR\vgpuRequired\x12\x19\n" +
	"\bgpu_type\x18\x04 \x01(\tR\agpuType\x12\"\n" +
	"\rmax_memory_mb\x18\x05 \x01(\x05R\vmaxMemoryMb\x12\x1e\n" +
	"\vmax_disk_mb\x18\x06 \x01(\x05R\tmaxDiskMb\x12%\n" +
	"\x0enetwork_access\x18\a \x01(\bR\rnetworkAccess\x12c\n" +
	"\x10binary_checksums\x18\b \x03(\v28.lettuce.volunteer.v1.ExecutionSpec.BinaryChecksumsEntryR\x0fbinaryChecksums\x1a;\n" +
	"\rBinariesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14BinaryChecksumsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12GetHeadInfoRequest\"\xcf\x02\n" +
	"\x13GetHeadInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x124\n" +
	"\x05leafs\x18\x04 \x03(\v2\x1e.lettuce.volunteer.v1.LeafInfoR\x05leafs\x12s\n" +
	"\x14default_leaf_weights\x18\x05 \x03(\v2A.lettuce.volunteer.v1.GetHeadInfoResponse.DefaultLeafWeightsEntryR\x12defaultLeafWeights\x1aE\n" +
	"\x17DefaultLeafWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xc8\x03\n" +
	"\bLeafInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rresearch_area\x18\x05 \x03(\tR\fresearchArea\x12!\n" +
	"\ftask_pattern\x18\x06 \x01(\tR\vtaskPattern\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12*\n" +
	"\x11queued_work_units\x18\b \x01(\x05R\x0fqueuedWorkUnits\x12+\n" +
	"\x11active_volunteers\x18\t \x01(\x05R\x10activeVolunteers\x12J\n" +
	"\x0eexecution_spec\x18\n" +
	" \x01(\v2#.lettuce.volunteer.v1.ExecutionSpecR\rexecutionSpec\x12<\n" +
	"\x1aestimated_duration_seconds\x18\v \x01(\x01R\x18estimatedDurationSeconds\x12!\n" +
	"\factive_hosts\x18\f \x01(\x05R\vactiveHosts\"\x94\x01\n" +
	"\x16AbandonWorkUnitRequest\x12 \n" +
	"\fwork_unit_id\x18\x01 \x01(\tR\n" +
	"workUnitId\x12!\n" +
	"\fvolunteer_id\x18\x02 \x01(\tR\vvolunteerId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"O\n" +
	"\x17AbandonWorkUnitResponse\x12\x1a\n" +
	"\brequeued\x18\x01 \x01(\bR\brequeued\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1a\n" +
	"\x18GetMyContributionRequest\"\xfd\x02\n" +
	"\x19GetMyContributionResponse\x12!\n" +
	"\fvolunteer_id\x18\x01 \x01(\tR\vvolunteerId\x12!\n" +
	"\ftotal_credit\x18\x02 \x01(\x01R\vtotalCredit\x12?\n" +
	"\aby_leaf\x18\x03 \x03(\v2&.lettuce.volunteer.v1.LeafContributionR\x06byLeaf\x12X\n" +
	"\x10by_resource_type\x18\x04 \x03(\v2..lettuce.volunteer.v1.ResourceTypeContributionR\x0ebyResourceType\x12=\n" +
	"\x05daily\x18\x05 \x03(\v2'.lettuce.volunteer.v1.DailyContributionR\x05daily\x12@\n" +
	"\x06weekly\x18\x06 \x03(\v2(.lettuce.volunteer.v1.WeeklyContributionR\x06weekly\"\xc1\x01\n" +
	"\x10LeafContribution\x12\x17\n" +
	"\aleaf_id\x18\x01 \x01(\tR\x06leafId\x12\x1b\n" +
	"\tleaf_name\x18\x02 \x01(\tR\bleafName\x12\x16\n" +
	"\x06credit\x18\x03 \x01(\x01R\x06credit\x12\x1d\n" +
	"\n" +
	"work_units\x18\x04 \x01(\x05R\tworkUnits\x12\x1f\n" +
	"\vcpu_seconds\x18\x05 \x01(\x01R\n" +
	"cpuSeconds\x12\x1f\n" +
	"\vgpu_seconds\x18\x06 \x01(\x01R\n" +
	"gpuSeconds\"v\n" +
	"\x18ResourceTypeContribution\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06credit\x18\x02 \x01(\x01R\x06credit\x12\x1d\n" +
	"\n" +
	"work_units\x18\x03 \x01(\x05R\tworkUnits\"?\n" +
	"\x11DailyContribution\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06credit\x18\x02 \x01(\x01R\x06credit\"K\n" +
	"\x12WeeklyContribution\x12\x1d\n" +
	"\n" +
	"week_start\x18\x01 \x01(\tR\tweekStart\x12\x16\n" +
	"\x06credit\x18\x02 \x01(\x01R\x06credit2\xc4\t\n" +
	"\x10VolunteerService\x12n\n" +
	"\x0fGetServerStatus\x12,.lettuce.volunteer.v1.GetServerStatusRequest\x1a-.lettuce.volunteer.v1.GetServerStatusResponse\x12t\n" +
	"\x11RegisterVolunteer\x12..lettuce.volunteer.v1.RegisterVolunteerRequest\x1a/.lettuce.volunteer.v1.RegisterVolunteerResponse\x12n\n" +
	"\x0fRequestWorkUnit\x12,.lettuce.volunteer.v1.RequestWorkUnitRequest\x1a-.lettuce.volunteer.v1.RequestWorkUnitResponse\x12e\n" +
	"\fSubmitResult\x12).lettuce.volunteer.v1.SubmitResultRequest\x1a*.lettuce.volunteer.v1.SubmitResultResponse\x12\\\n" +
	"\tStartWork\x12&.lettuce.volunteer.v1.StartWorkRequest\x1a'.lettuce.volunteer.v1.StartWorkResponse\x12t\n" +
	"\x11GetWorkUnitStatus\x12..lettuce.volunteer.v1.GetWorkUnitStatusRequest\x1a/.lettuce.volunteer.v1.GetWorkUnitStatusResponse\x12b\n" +
	"\vGetHeadInfo\x12(.lettuce.volunteer.v1.GetHeadInfoRequest\x1a).lettuce.volunteer.v1.GetHeadInfoResponse\x12k\n" +
	"\x0eSaveCheckpoint\x12+.lettuce.volunteer.v1.SaveCheckpointRequest\x1a,.lettuce.volunteer.v1.SaveCheckpointResponse\x12h\n" +
	"\rGetCheckpoint\x12*.lettuce.volunteer.v1.GetCheckpointRequest\x1a+.lettuce.volunteer.v1.GetCheckpointResponse\x12n\n" +
	"\x0fAbandonWorkUnit\x12,.lettuce.volunteer.v1.AbandonWorkUnitRequest\x1a-.lettuce.volunteer.v1.AbandonWorkUnitResponse\x12t\n" +
	"\x11GetMyContribution\x12..lettuce.volunteer.v1.GetMyContributionRequest\x1a/.lettuce.volunteer.v1.GetMyContributionResponseBFZDgithub.com/lettuce-compute/infrastructure/proto/lettuce/v1;lettucev1b\x06proto3"

var (
	file_proto_lettuce_v1_volunteer_proto_rawDescOnce sync.Once
	file_proto_lettuce_v1_volunteer_proto_rawDescData []byte
)

func file_proto_lettuce_v1_volunteer_proto_rawDescGZIP() []byte {
	file_proto_lettuce_v1_volunteer_proto_rawDescOnce.Do(func() {
		file_proto_lettuce_v1_volunteer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lettuce_v1_volunteer_proto_rawDesc), len(file_proto_lettuce_v1_volunteer_proto_rawDesc)))
	})
	return file_proto_lettuce_v1_volunteer_proto_rawDescData
}

var file_proto_lettuce_v1_volunteer_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_lettuce_v1_volunteer_proto_goTypes = []any{
	(*GetServerStatusRequest)(nil),    // 0: lettuce.volunteer.v1.GetServerStatusRequest
	(*GetServerStatusResponse)(nil),   // 1: lettuce.volunteer.v1.GetServerStatusResponse
	(*RegisterVolunteerRequest)(nil),  // 2: lettuce.volunteer.v1.RegisterVolunteerRequest
	(*RegisterVolunteerResponse)(nil), // 3: lettuce.volunteer.v1.RegisterVolunteerResponse
	(*RequestWorkUnitRequest)(nil),    // 4: lettuce.volunteer.v1.RequestWorkUnitRequest
	(*RequestWorkUnitResponse)(nil),   // 5: lettuce.volunteer.v1.RequestWorkUnitResponse
	(*WorkUnitAssignment)(nil),        // 6: lettuce.volunteer.v1.WorkUnitAssignment
	(*SubmitResultRequest)(nil),       // 7: lettuce.volunteer.v1.SubmitResultRequest
	(*SubmitResultResponse)(nil),      // 8: lettuce.volunteer.v1.SubmitResultResponse
	(*StartWorkRequest)(nil),          // 9: lettuce.volunteer.v1.StartWorkRequest
	(*StartWorkResponse)(nil),         // 10: lettuce.volunteer.v1.StartWorkResponse
	(*GetWorkUnitStatusRequest)(nil),  // 11: lettuce.volunteer.v1.GetWorkUnitStatusRequest
	(*GetWorkUnitStatusResponse)(nil), // 12: lettuce.volunteer.v1.GetWorkUnitStatusResponse
	(*SaveCheckpointRequest)(nil),     // 13: lettuce.volunteer.v1.SaveCheckpointRequest
	(*SaveCheckpointResponse)(nil),    // 14: lettuce.volunteer.v1.SaveCheckpointResponse
	(*GetCheckpointRequest)(nil),      // 15: lettuce.volunteer.v1.GetCheckpointRequest
	(*GetCheckpointResponse)(nil),     // 16: lettuce.volunteer.v1.GetCheckpointResponse
	(*HardwareCapabilities)(nil),      // 17: lettuce.volunteer.v1.HardwareCapabilities
	(*GpuInfo)(nil),                   // 18: lettuce.volunteer.v1.GpuInfo
	(*ExecutionMetadata)(nil),         // 19: lettuce.volunteer.v1.ExecutionMetadata
	(*ExecutionSpec)(nil),             // 20: lettuce.volunteer.v1.ExecutionSpec
	(*GetHeadInfoRequest)(nil),        // 21: lettuce.volunteer.v1.GetHeadInfoRequest
	(*GetHeadInfoResponse)(nil),       // 22: lettuce.volunteer.v1.GetHeadInfoResponse
	(*LeafInfo)(nil),                  // 23: lettuce.volunteer.v1.LeafInfo
	(*AbandonWorkUnitRequest)(nil),    // 24: lettuce.volunteer.v1.AbandonWorkUnitRequest
	(*AbandonWorkUnitResponse)(nil),   // 25: lettuce.volunteer.v1.AbandonWorkUnitResponse
	(*GetMyContributionRequest)(nil),  // 26: lettuce.volunteer.v1.GetMyContributionRequest
	(*GetMyContributionResponse)(nil), // 27: lettuce.volunteer.v1.GetMyContributionResponse
	(*LeafContribution)(nil),          // 28: lettuce.volunteer.v1.LeafContribution
	(*ResourceTypeContribution)(nil),  // 29: lettuce.volunteer.v1.ResourceTypeContribution
	(*DailyContribution)(nil),         // 30: lettuce.volunteer.v1.DailyContribution
	(*WeeklyContribution)(nil),        // 31: lettuce.volunteer.v1.WeeklyContribution
	nil,                               // 32: lettuce.volunteer.v1.WorkUnitAssignment.EnvVarsEntry
	nil,                               // 33: lettuce.volunteer.v1.ExecutionSpec.BinariesEntry
	nil,                               // 34: lettuce.volunteer.v1.ExecutionSpec.BinaryChecksumsEntry
	nil,                               // 35: lettuce.volunteer.v1.GetHeadInfoResponse.DefaultLeafWeightsEntry
}
var file_proto_lettuce_v1_volunteer_proto_depIdxs = []int32{
	17, // 0: lettuce.volunteer.v1.RegisterVolunteerRequest.hardware:type_name -> lettuce.volunteer.v1.HardwareCapabilities
	17, // 1: lettuce.volunteer.v1.RequestWorkUnitRequest.current_available:type_name -> lettuce.volunteer.v1.HardwareCapabilities
	6,  // 2: lettuce.volunteer.v1.RequestWorkUnitResponse.assignments:type_name -> lettuce.volunteer.v1.WorkUnitAssignment
	32, // 3: lettuce.volunteer.v1.WorkUnitAssignment.env_vars:type_name -> lettuce.volunteer.v1.WorkUnitAssignment.EnvVarsEntry
	20, // 4: lettuce.volunteer.v1.WorkUnitAssignment.execution_spec:type_name -> lettuce.volunteer.v1.ExecutionSpec
	19, // 5: lettuce.volunteer.v1.SubmitResultRequest.metadata:type_name -> lettuce.volunteer.v1.ExecutionMetadata
	18, // 6: lettuce.volunteer.v1.HardwareCapabilities.gpus:type_name -> lettuce.volunteer.v1.GpuInfo
	33, // 7: lettuce.volunteer.v1.ExecutionSpec.binaries:type_name -> lettuce.volunteer.v1.ExecutionSpec.BinariesEntry
	34, // 8: lettuce.volunteer.v1.ExecutionSpec.binary_checksums:type_name -> lettuce.volunteer.v1.ExecutionSpec.BinaryChecksumsEntry
	23, // 9: lettuce.volunteer.v1.GetHeadInfoResponse.leafs:type_name -> lettuce.volunteer.v1.LeafInfo
	35, // 10: lettuce.volunteer.v1.GetHeadInfoResponse.default_leaf_weights:type_name -> lettuce.volunteer.v1.GetHeadInfoResponse.DefaultLeafWeightsEntry
	20, // 11: lettuce.volunteer.v1.LeafInfo.execution_spec:type_name -> lettuce.volunteer.v1.ExecutionSpec
	28, // 12: lettuce.volunteer.v1.GetMyContributionResponse.by_leaf:type_name -> lettuce.volunteer.v1.LeafContribution
	29, // 13: lettuce.volunteer.v1.GetMyContributionResponse.by_resource_type:type_name -> lettuce.volunteer.v1.ResourceTypeContribution
	30, // 14: lettuce.volunteer.v1.GetMyContributionResponse.daily:type_name -> lettuce.volunteer.v1.DailyContribution
	31, // 15: lettuce.volunteer.v1.GetMyContributionResponse.weekly:type_name -> lettuce.volunteer.v1.WeeklyContribution
	0,  // 16: lettuce.volunteer.v1.VolunteerService.GetServerStatus:input_type -> lettuce.volunteer.v1.GetServerStatusRequest
	2,  // 17: lettuce.volunteer.v1.VolunteerService.RegisterVolunteer:input_type -> lettuce.volunteer.v1.RegisterVolunteerRequest
	4,  // 18: lettuce.volunteer.v1.VolunteerService.RequestWorkUnit:input_type -> lettuce.volunteer.v1.RequestWorkUnitRequest
	7,  // 19: lettuce.volunteer.v1.VolunteerService.SubmitResult:input_type -> lettuce.volunteer.v1.SubmitResultRequest
	9,  // 20: lettuce.volunteer.v1.VolunteerService.StartWork:input_type -> lettuce.volunteer.v1.StartWorkRequest
	11, // 21: lettuce.volunteer.v1.VolunteerService.GetWorkUnitStatus:input_type -> lettuce.volunteer.v1.GetWorkUnitStatusRequest
	21, // 22: lettuce.volunteer.v1.VolunteerService.GetHeadInfo:input_type -> lettuce.volunteer.v1.GetHeadInfoRequest
	13, // 23: lettuce.volunteer.v1.VolunteerService.SaveCheckpoint:input_type -> lettuce.volunteer.v1.SaveCheckpointRequest
	15, // 24: lettuce.volunteer.v1.VolunteerService.GetCheckpoint:input_type -> lettuce.volunteer.v1.GetCheckpointRequest
	24, // 25: lettuce.volunteer.v1.VolunteerService.AbandonWorkUnit:input_type -> lettuce.volunteer.v1.AbandonWorkUnitRequest
	26, // 26: lettuce.volunteer.v1.VolunteerService.GetMyContribution:input_type -> lettuce.volunteer.v1.GetMyContributionRequest
	1,  // 27: lettuce.volunteer.v1.VolunteerService.GetServerStatus:output_type -> lettuce.volunteer.v1.GetServerStatusResponse
	3,  // 28: lettuce.volunteer.v1.VolunteerService.RegisterVolunteer:output_type -> lettuce.volunteer.v1.RegisterVolunteerResponse
	5,  // 29: lettuce.volunteer.v1.VolunteerService.RequestWorkUnit:output_type -> lettuce.volunteer.v1.RequestWorkUnitResponse
	8,  // 30: lettuce.volunteer.v1.VolunteerService.SubmitResult:output_type -> lettuce.volunteer.v1.SubmitResultResponse
	10, // 31: lettuce.volunteer.v1.VolunteerService.StartWork:output_type -> lettuce.volunteer.v1.StartWorkResponse
	12, // 32: lettuce.volunteer.v1.VolunteerService.GetWorkUnitStatus:output_type -> lettuce.volunteer.v1.GetWorkUnitStatusResponse
	22, // 33: lettuce.volunteer.v1.VolunteerService.GetHeadInfo:output_type -> lettuce.volunteer.v1.GetHeadInfoResponse
	14, // 34: lettuce.volunteer.v1.VolunteerService.SaveCheckpoint:output_type -> lettuce.volunteer.v1.SaveCheckpointResponse
	16, // 35: lettuce.volunteer.v1.VolunteerService.GetCheckpoint:output_type -> lettuce.volunteer.v1.GetCheckpointResponse
	25, // 36: lettuce.volunteer.v1.VolunteerService.AbandonWorkUnit:output_type -> lettuce.volunteer.v1.AbandonWorkUnitResponse
	27, // 37: lettuce.volunteer.v1.VolunteerService.GetMyContribution:output_type -> lettuce.volunteer.v1.GetMyContributionResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_lettuce_v1_volunteer_proto_init() }
func file_proto_lettuce_v1_volunteer_proto_init() {
	if File_proto_lettuce_v1_volunteer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lettuce_v1_volunteer_proto_rawDesc), len(file_proto_lettuce_v1_volunteer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lettuce_v1_volunteer_proto_goTypes,
		DependencyIndexes: file_proto_lettuce_v1_volunteer_proto_depIdxs,
		MessageInfos:      file_proto_lettuce_v1_volunteer_proto_msgTypes,
	}.Build()
	File_proto_lettuce_v1_volunteer_proto = out.File
	file_proto_lettuce_v1_volunteer_proto_goTypes = nil
	file_proto_lettuce_v1_volunteer_proto_depIdxs = nil
}
