// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/lettuce/v1/volunteer.proto

package lettucev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VolunteerService_GetServerStatus_FullMethodName   = "/lettuce.volunteer.v1.VolunteerService/GetServerStatus"
	VolunteerService_RegisterVolunteer_FullMethodName = "/lettuce.volunteer.v1.VolunteerService/RegisterVolunteer"
	VolunteerService_RequestWorkUnit_FullMethodName   = "/lettuce.volunteer.v1.VolunteerService/RequestWorkUnit"
	VolunteerService_SubmitResult_FullMethodName      = "/lettuce.volunteer.v1.VolunteerService/SubmitResult"
	VolunteerService_Heartbeat_FullMethodName         = "/lettuce.volunteer.v1.VolunteerService/Heartbeat"
	VolunteerService_GetWorkUnitStatus_FullMethodName = "/lettuce.volunteer.v1.VolunteerService/GetWorkUnitStatus"
	VolunteerService_GetHeadInfo_FullMethodName       = "/lettuce.volunteer.v1.VolunteerService/GetHeadInfo"
	VolunteerService_SaveCheckpoint_FullMethodName    = "/lettuce.volunteer.v1.VolunteerService/SaveCheckpoint"
	VolunteerService_GetCheckpoint_FullMethodName     = "/lettuce.volunteer.v1.VolunteerService/GetCheckpoint"
	VolunteerService_AbandonWorkUnit_FullMethodName   = "/lettuce.volunteer.v1.VolunteerService/AbandonWorkUnit"
)

// VolunteerServiceClient is the client API for VolunteerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VolunteerServiceClient interface {
	// Returns server status and version information.
	GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*GetServerStatusResponse, error)
	// Register or update volunteer capabilities.
	// Called on first connection and when hardware config changes.
	// Upserts by public_key: new key = register, existing key = update.
	RegisterVolunteer(ctx context.Context, in *RegisterVolunteerRequest, opts ...grpc.CallOption) (*RegisterVolunteerResponse, error)
	// Request a work unit matching volunteer capabilities.
	// Returns NOT_FOUND status if no matching work available.
	// Volunteer should poll with exponential backoff (1s, 2s, 4s, max 30s).
	RequestWorkUnit(ctx context.Context, in *RequestWorkUnitRequest, opts ...grpc.CallOption) (*RequestWorkUnitResponse, error)
	// Submit result for a completed work unit.
	// Includes output data and execution metadata.
	SubmitResult(ctx context.Context, in *SubmitResultRequest, opts ...grpc.CallOption) (*SubmitResultResponse, error)
	// Send heartbeat during work unit execution.
	// Must be called at leaf's configured interval (default: 5 min).
	// Missing heartbeats trigger work unit abandonment.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Query status of a specific work unit.
	GetWorkUnitStatus(ctx context.Context, in *GetWorkUnitStatusRequest, opts ...grpc.CallOption) (*GetWorkUnitStatusResponse, error)
	// Get head identity and active leaf discovery info.
	GetHeadInfo(ctx context.Context, in *GetHeadInfoRequest, opts ...grpc.CallOption) (*GetHeadInfoResponse, error)
	// Save a checkpoint for a running work unit.
	SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error)
	// Get the latest checkpoint for a work unit.
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error)
	// Abandon a work unit that the volunteer cannot execute (e.g., prepare failed).
	// Server marks the assignment as ABANDONED and requeues the work unit.
	AbandonWorkUnit(ctx context.Context, in *AbandonWorkUnitRequest, opts ...grpc.CallOption) (*AbandonWorkUnitResponse, error)
}

type volunteerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVolunteerServiceClient(cc grpc.ClientConnInterface) VolunteerServiceClient {
	return &volunteerServiceClient{cc}
}

func (c *volunteerServiceClient) GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*GetServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerStatusResponse)
	err := c.cc.Invoke(ctx, VolunteerService_GetServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) RegisterVolunteer(ctx context.Context, in *RegisterVolunteerRequest, opts ...grpc.CallOption) (*RegisterVolunteerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterVolunteerResponse)
	err := c.cc.Invoke(ctx, VolunteerService_RegisterVolunteer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) RequestWorkUnit(ctx context.Context, in *RequestWorkUnitRequest, opts ...grpc.CallOption) (*RequestWorkUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestWorkUnitResponse)
	err := c.cc.Invoke(ctx, VolunteerService_RequestWorkUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) SubmitResult(ctx context.Context, in *SubmitResultRequest, opts ...grpc.CallOption) (*SubmitResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResultResponse)
	err := c.cc.Invoke(ctx, VolunteerService_SubmitResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, VolunteerService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) GetWorkUnitStatus(ctx context.Context, in *GetWorkUnitStatusRequest, opts ...grpc.CallOption) (*GetWorkUnitStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkUnitStatusResponse)
	err := c.cc.Invoke(ctx, VolunteerService_GetWorkUnitStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) GetHeadInfo(ctx context.Context, in *GetHeadInfoRequest, opts ...grpc.CallOption) (*GetHeadInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHeadInfoResponse)
	err := c.cc.Invoke(ctx, VolunteerService_GetHeadInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCheckpointResponse)
	err := c.cc.Invoke(ctx, VolunteerService_SaveCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckpointResponse)
	err := c.cc.Invoke(ctx, VolunteerService_GetCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volunteerServiceClient) AbandonWorkUnit(ctx context.Context, in *AbandonWorkUnitRequest, opts ...grpc.CallOption) (*AbandonWorkUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonWorkUnitResponse)
	err := c.cc.Invoke(ctx, VolunteerService_AbandonWorkUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolunteerServiceServer is the server API for VolunteerService service.
// All implementations must embed UnimplementedVolunteerServiceServer
// for forward compatibility.
type VolunteerServiceServer interface {
	// Returns server status and version information.
	GetServerStatus(context.Context, *GetServerStatusRequest) (*GetServerStatusResponse, error)
	// Register or update volunteer capabilities.
	// Called on first connection and when hardware config changes.
	// Upserts by public_key: new key = register, existing key = update.
	RegisterVolunteer(context.Context, *RegisterVolunteerRequest) (*RegisterVolunteerResponse, error)
	// Request a work unit matching volunteer capabilities.
	// Returns NOT_FOUND status if no matching work available.
	// Volunteer should poll with exponential backoff (1s, 2s, 4s, max 30s).
	RequestWorkUnit(context.Context, *RequestWorkUnitRequest) (*RequestWorkUnitResponse, error)
	// Submit result for a completed work unit.
	// Includes output data and execution metadata.
	SubmitResult(context.Context, *SubmitResultRequest) (*SubmitResultResponse, error)
	// Send heartbeat during work unit execution.
	// Must be called at leaf's configured interval (default: 5 min).
	// Missing heartbeats trigger work unit abandonment.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Query status of a specific work unit.
	GetWorkUnitStatus(context.Context, *GetWorkUnitStatusRequest) (*GetWorkUnitStatusResponse, error)
	// Get head identity and active leaf discovery info.
	GetHeadInfo(context.Context, *GetHeadInfoRequest) (*GetHeadInfoResponse, error)
	// Save a checkpoint for a running work unit.
	SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error)
	// Get the latest checkpoint for a work unit.
	GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error)
	// Abandon a work unit that the volunteer cannot execute (e.g., prepare failed).
	// Server marks the assignment as ABANDONED and requeues the work unit.
	AbandonWorkUnit(context.Context, *AbandonWorkUnitRequest) (*AbandonWorkUnitResponse, error)
	mustEmbedUnimplementedVolunteerServiceServer()
}

// UnimplementedVolunteerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolunteerServiceServer struct{}

func (UnimplementedVolunteerServiceServer) GetServerStatus(context.Context, *GetServerStatusRequest) (*GetServerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerStatus not implemented")
}
func (UnimplementedVolunteerServiceServer) RegisterVolunteer(context.Context, *RegisterVolunteerRequest) (*RegisterVolunteerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterVolunteer not implemented")
}
func (UnimplementedVolunteerServiceServer) RequestWorkUnit(context.Context, *RequestWorkUnitRequest) (*RequestWorkUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestWorkUnit not implemented")
}
func (UnimplementedVolunteerServiceServer) SubmitResult(context.Context, *SubmitResultRequest) (*SubmitResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResult not implemented")
}
func (UnimplementedVolunteerServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedVolunteerServiceServer) GetWorkUnitStatus(context.Context, *GetWorkUnitStatusRequest) (*GetWorkUnitStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkUnitStatus not implemented")
}
func (UnimplementedVolunteerServiceServer) GetHeadInfo(context.Context, *GetHeadInfoRequest) (*GetHeadInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHeadInfo not implemented")
}
func (UnimplementedVolunteerServiceServer) SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCheckpoint not implemented")
}
func (UnimplementedVolunteerServiceServer) GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedVolunteerServiceServer) AbandonWorkUnit(context.Context, *AbandonWorkUnitRequest) (*AbandonWorkUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbandonWorkUnit not implemented")
}
func (UnimplementedVolunteerServiceServer) mustEmbedUnimplementedVolunteerServiceServer() {}
func (UnimplementedVolunteerServiceServer) testEmbeddedByValue()                          {}

// UnsafeVolunteerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolunteerServiceServer will
// result in compilation errors.
type UnsafeVolunteerServiceServer interface {
	mustEmbedUnimplementedVolunteerServiceServer()
}

func RegisterVolunteerServiceServer(s grpc.ServiceRegistrar, srv VolunteerServiceServer) {
	// If the following call panics, it indicates UnimplementedVolunteerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolunteerService_ServiceDesc, srv)
}

func _VolunteerService_GetServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).GetServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_GetServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).GetServerStatus(ctx, req.(*GetServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_RegisterVolunteer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterVolunteerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).RegisterVolunteer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_RegisterVolunteer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).RegisterVolunteer(ctx, req.(*RegisterVolunteerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_RequestWorkUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestWorkUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).RequestWorkUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_RequestWorkUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).RequestWorkUnit(ctx, req.(*RequestWorkUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_SubmitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).SubmitResult(ctx, req.(*SubmitResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_GetWorkUnitStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkUnitStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).GetWorkUnitStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_GetWorkUnitStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).GetWorkUnitStatus(ctx, req.(*GetWorkUnitStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_GetHeadInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeadInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).GetHeadInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_GetHeadInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).GetHeadInfo(ctx, req.(*GetHeadInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_SaveCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).SaveCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_SaveCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).SaveCheckpoint(ctx, req.(*SaveCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_GetCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).GetCheckpoint(ctx, req.(*GetCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolunteerService_AbandonWorkUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonWorkUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolunteerServiceServer).AbandonWorkUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolunteerService_AbandonWorkUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolunteerServiceServer).AbandonWorkUnit(ctx, req.(*AbandonWorkUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VolunteerService_ServiceDesc is the grpc.ServiceDesc for VolunteerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolunteerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lettuce.volunteer.v1.VolunteerService",
	HandlerType: (*VolunteerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerStatus",
			Handler:    _VolunteerService_GetServerStatus_Handler,
		},
		{
			MethodName: "RegisterVolunteer",
			Handler:    _VolunteerService_RegisterVolunteer_Handler,
		},
		{
			MethodName: "RequestWorkUnit",
			Handler:    _VolunteerService_RequestWorkUnit_Handler,
		},
		{
			MethodName: "SubmitResult",
			Handler:    _VolunteerService_SubmitResult_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _VolunteerService_Heartbeat_Handler,
		},
		{
			MethodName: "GetWorkUnitStatus",
			Handler:    _VolunteerService_GetWorkUnitStatus_Handler,
		},
		{
			MethodName: "GetHeadInfo",
			Handler:    _VolunteerService_GetHeadInfo_Handler,
		},
		{
			MethodName: "SaveCheckpoint",
			Handler:    _VolunteerService_SaveCheckpoint_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _VolunteerService_GetCheckpoint_Handler,
		},
		{
			MethodName: "AbandonWorkUnit",
			Handler:    _VolunteerService_AbandonWorkUnit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lettuce/v1/volunteer.proto",
}
